### ISSUE TITLE
Assets precompile task breaks on pghero >= 1.5

### ISSUE THREAD

**Issue by raivil** [ankane/pghero#103]
Hi,

I'm upgrading pghero from 1.2 to the latest version and just found the exception below while precompiling assets. I've tested all versions from 1.2 to 1.6.2 and the error starts with version 1.5. Could you help me fix it? It may also be a composite_primary_keys issue. I'm still investigating.

Thank you.

A workaround is to specify `PGHERO_DATABASE_URL` while precompiling assets.
```
Rails 3.2.22.4
PgHero 1.6.2
composite_primary_keys 5.0.14
```

```
 $ bundle exec rake assets:precompile
/Users/user/.rvm/rubies/ruby-2.2.5/bin/ruby /Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
rake aborted!
Airbrake::Error: the 'default' notifier isn't configured
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/airbrake-ruby-1.2.0/lib/airbrake-ruby.rb:289:in `call_notifier'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/airbrake-ruby-1.2.0/lib/airbrake-ruby.rb:239:in `build_notice'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/airbrake-5.1.0/lib/airbrake/rake/task_ext.rb:21:in `rescue in execute'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/airbrake-5.1.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Airbrake::Error: the 'default' notifier isn't configured
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/airbrake-ruby-1.2.0/lib/airbrake-ruby.rb:289:in `call_notifier'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/airbrake-ruby-1.2.0/lib/airbrake-ruby.rb:239:in `build_notice'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/airbrake-5.1.0/lib/airbrake/rake/task_ext.rb:21:in `rescue in execute'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/airbrake-5.1.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/actionpack-3.2.22.4/lib/sprockets/assets.rake:60:in `block (3 levels) in <top (required)>'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/airbrake-5.1.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
NoMethodError: undefined method `spec' for nil:NilClass
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/composite_primary_keys-5.0.14/lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb:39:in `connection_config'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/pghero-1.6.2/lib/pghero.rb:77:in `config'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/pghero-1.6.2/lib/pghero/engine.rb:15:in `block in <class:Engine>'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/railties-3.2.22.4/lib/rails/initializable.rb:30:in `instance_exec'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/railties-3.2.22.4/lib/rails/initializable.rb:30:in `run'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/railties-3.2.22.4/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/railties-3.2.22.4/lib/rails/initializable.rb:54:in `each'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/railties-3.2.22.4/lib/rails/initializable.rb:54:in `run_initializers'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/railties-3.2.22.4/lib/rails/application.rb:136:in `initialize!'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/actionpack-3.2.22.4/lib/sprockets/assets.rake:95:in `block (2 levels) in <top (required)>'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/airbrake-5.1.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/actionpack-3.2.22.4/lib/sprockets/assets.rake:60:in `block (3 levels) in <top (required)>'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/airbrake-5.1.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => assets:precompile:all
(See full trace by running task with --trace)
rake aborted!
Airbrake::Error: the 'default' notifier isn't configured
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/airbrake-ruby-1.2.0/lib/airbrake-ruby.rb:289:in `call_notifier'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/airbrake-ruby-1.2.0/lib/airbrake-ruby.rb:239:in `build_notice'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/airbrake-5.1.0/lib/airbrake/rake/task_ext.rb:21:in `rescue in execute'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/airbrake-5.1.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/bin/ruby_executable_hooks:15:in `<main>'
Command failed with status (1): [/Users/user/.rvm/rubies/ruby-2.2.5/bin/r...]
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/actionpack-3.2.22.4/lib/sprockets/assets.rake:12:in `ruby_rake_task'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/actionpack-3.2.22.4/lib/sprockets/assets.rake:21:in `invoke_or_reboot_rake_task'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/actionpack-3.2.22.4/lib/sprockets/assets.rake:29:in `block (2 levels) in <top (required)>'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/airbrake-5.1.0/lib/airbrake/rake/task_ext.rb:19:in `execute'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/bin/ruby_executable_hooks:15:in `eval'
/Users/user/.rvm/gems/ruby-2.2.5@gems-v1.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
```

**Comment by ankane** [comment]
Let me know what you find.

**Comment by raivil** [comment]
@ankane 

I did some investigation and the issue seems to be related to rails initialization and the given group.

here's rails 3.2 code (railties-3.2.22.4/lib/rails/application.rb:130)
```ruby
# Initialize the application passing the given group. By default, the
# group is :default but sprockets precompilation passes group equals
# to assets if initialize_on_precompile is false to avoid booting the
# whole app.
def initialize!(group=:default) #:nodoc:
  raise "Application has been already initialized." if @initialized
  run_initializers(group, self)
  @initialized = true
  self
end
```


PgHero uses `initializer "pghero", group: :all` and while executing `assets:precompile`, the rails app is initialized with `Rails.application.initialize!(:assets)`.

Looks like precompilattion won't load the entire app (database connections) and will cause the error.

I'm not sure this is an optimal solution but using `initializer "pghero", group: :default` seems to fix the issue.

**Comment by ankane** [comment]
Hey @raivil, thanks for reporting back. I'm a bit worried about the impact of changing it to use the `default` group. Since Rails 3 is no longer officially supported (by Rails), I don't think it's worth trying to fix.

**Comment by raivil** [comment]
Hi @ankane I agree with you.  It's not worth trying to fix it for rails 3.x.
In fact, my project has started migration to latest 4.2 before jumping to rails 5. 
If I face this issue on any recent versions, I'll let you know.

A workaround for rails 3.x is to set PGHERO_DATABASE_URL.
If deploying with Capistrano use `set :default_environment`
```
set :default_environment,  "PGHERO_DATABASE_URL" => "XXX"
```
