### ISSUE TITLE
Multiple databases?

### ISSUE THREAD

**Issue by nhumrich** [ankane/pghero#130]
The readme (docker) says that in order to use multiple databases, you need a pghero.yml file

I created a yml file that looks like:

```yaml
databases:
  foo:
    url: postgres://postgres:postgres@localhost/foodb
  bar:
    url: postgres://postgres:postgres@localhost/bardb
```

But I get the following error on startup:
```
[7] Puma starting in cluster mode...
[7] * Version 3.8.2 (ruby 2.3.1-p112), codename: Sassy Salamander
[7] * Min threads: 1, max threads: 16
[7] * Environment: development
[7] * Process workers: 3
[7] * Preloading application
[7] ! Unable to load application: RuntimeError: Cannot load `Rails.application.database_configuration`:
Could not load database configuration. No such file - ["config/database.yml"]
/usr/local/bundle/gems/railties-5.1.0/lib/rails/application/configuration.rb:139:in `database_configuration': Cannot load `Rails.application.database_configuration`: (RuntimeError)
Could not load database configuration. No such file - ["config/database.yml"]
        from /usr/local/bundle/gems/activerecord-5.1.0/lib/active_record/railtie.rb:121:in `block (2 levels) in <class:Railtie>'
        from /usr/local/bundle/gems/activesupport-5.1.0/lib/active_support/lazy_load_hooks.rb:45:in `instance_eval'
        from /usr/local/bundle/gems/activesupport-5.1.0/lib/active_support/lazy_load_hooks.rb:45:in `execute_hook'
        from /usr/local/bundle/gems/activesupport-5.1.0/lib/active_support/lazy_load_hooks.rb:35:in `block in on_load'
        from /usr/local/bundle/gems/activesupport-5.1.0/lib/active_support/lazy_load_hooks.rb:34:in `each'
        from /usr/local/bundle/gems/activesupport-5.1.0/lib/active_support/lazy_load_hooks.rb:34:in `on_load'
        from /usr/local/bundle/gems/activerecord-5.1.0/lib/active_record/railtie.rb:120:in `block in <class:Railtie>'
        from /usr/local/bundle/gems/railties-5.1.0/lib/rails/initializable.rb:30:in `instance_exec'
        from /usr/local/bundle/gems/railties-5.1.0/lib/rails/initializable.rb:30:in `run'
        from /usr/local/bundle/gems/railties-5.1.0/lib/rails/initializable.rb:59:in `block in run_initializers'
        from /usr/local/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
        from /usr/local/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each'
        from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `call'
        from /usr/local/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
        from /usr/local/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
        from /usr/local/bundle/gems/railties-5.1.0/lib/rails/initializable.rb:58:in `run_initializers'
        from /usr/local/bundle/gems/railties-5.1.0/lib/rails/application.rb:353:in `initialize!'
        from /app/config/environment.rb:5:in `<top (required)>'
        from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from config.ru:3:in `block in <main>'
        from /usr/local/bundle/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
        from /usr/local/bundle/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
        from config.ru:in `new'
        from config.ru:in `<main>'
        from /usr/local/bundle/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
        from /usr/local/bundle/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
        from /usr/local/bundle/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
        from /usr/local/bundle/gems/puma-3.8.2/lib/puma/configuration.rb:313:in `load_rackup'
        from /usr/local/bundle/gems/puma-3.8.2/lib/puma/configuration.rb:242:in `app'
        from /usr/local/bundle/gems/puma-3.8.2/lib/puma/runner.rb:138:in `load_and_bind'
        from /usr/local/bundle/gems/puma-3.8.2/lib/puma/cluster.rb:391:in `run'
        from /usr/local/bundle/gems/puma-3.8.2/lib/puma/launcher.rb:172:in `run'
        from /usr/local/bundle/gems/puma-3.8.2/lib/puma/cli.rb:77:in `run'
        from /usr/local/bundle/gems/puma-3.8.2/bin/puma:10:in `<top (required)>'
        from /usr/local/bundle/bin/puma:22:in `load'
        from /usr/local/bundle/bin/puma:22:in `<main>'
```

Looks like its reading from `database.yml`, not pghero.yml?
I tried mounting a file at that location as well with no luck.

**Comment by encryptblockr** [comment]
where is screenshot for multiple databases? I have a setup with multiple databases but i see the same GUI as single database, and it points to the primary database

any official or non-official screenshot showing this?
