### ISSUE TITLE
Sequences for other schemas are not found

### ISSUE THREAD

**Issue by jontonsoup** [ankane/pghero#142]
Just upgraded to V2. Thanks for all the hard work!

It seems like the sequences for the public schema and other schemas are getting confused and throwing a bug. Essentially, it is not finding sequences from other schemas. 

```
ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "price_archive_id_seq" does not exist 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  LINE 1: ...pen_order_id_seq UNION ALL SELECT last_value FROM price_arch... 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:                                                               ^ 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  : SELECT last_value FROM expanded_trade_id_seq UNION ALL SELECT last_value FROM historical_data_id_seq UNION ALL SELECT last_value FROM market_id_seq UNION ALL SELECT last_value FROM marketsnapshot_archive_id_seq UNION ALL SELECT last_value FROM marketsnapshot_archive_id_seq UNION ALL SELECT last_value FROM marketsnapshot_id_seq UNION ALL SELECT last_value FROM open_order_id_seq UNION ALL SELECT last_value FROM price_archive_id_seq UNION ALL SELECT last_value FROM price_id_seq UNION ALL SELECT last_value FROM runner_id_seq UNION ALL SELECT last_value FROM streaming_message_id_seq UNION ALL SELECT last_value FROM trade_id_seq UNION ALL SELECT last_value FROM venue_id_seq): 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activerecord (5.0.5) lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `async_exec' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activerecord (5.0.5) lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activerecord (5.0.5) lib/active_record/connection_adapters/abstract_adapter.rb:590:in `block in log' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activesupport (5.0.5) lib/active_support/notifications/instrumenter.rb:21:in `instrument' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activerecord (5.0.5) lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activerecord (5.0.5) lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activerecord (5.0.5) lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activerecord (5.0.5) lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activerecord (5.0.5) lib/active_record/connection_adapters/abstract/database_statements.rb:373:in `select' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activerecord (5.0.5) lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activerecord (5.0.5) lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  /usr/local/bundle/bundler/gems/pghero-34a116807899/lib/pghero/methods/basic.rb:56:in `select_all' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  /usr/local/bundle/bundler/gems/pghero-34a116807899/lib/pghero/methods/sequences.rb:32:in `sequences' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  /usr/local/bundle/bundler/gems/pghero-34a116807899/lib/pghero/methods/sequences.rb:40:in `sequence_danger' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  /usr/local/bundle/bundler/gems/pghero-34a116807899controllers/pg_hero/home_controller.rb:38:in `index' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/abstract_controller/base.rb:188:in `process_action' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_controller/metal/rendering.rb:30:in `process_action' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/abstract_controller/callbacks.rb:20:in `block in process_action' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activesupport (5.0.5) lib/active_support/callbacks.rb:126:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activesupport (5.0.5) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activesupport (5.0.5) lib/active_support/callbacks.rb:455:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activesupport (5.0.5) lib/active_support/callbacks.rb:101:in `__run_callbacks__' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activesupport (5.0.5) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activesupport (5.0.5) lib/active_support/callbacks.rb:90:in `run_callbacks' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/abstract_controller/callbacks.rb:19:in `process_action' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_controller/metal/rescue.rb:20:in `process_action' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activesupport (5.0.5) lib/active_support/notifications.rb:164:in `block in instrument' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activesupport (5.0.5) lib/active_support/notifications/instrumenter.rb:21:in `instrument' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activesupport (5.0.5) lib/active_support/notifications.rb:164:in `instrument' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_controller/metal/params_wrapper.rb:248:in `process_action' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  activerecord (5.0.5) lib/active_record/railties/controller_runtime.rb:18:in `process_action' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/abstract_controller/base.rb:126:in `process' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionview (5.0.5) lib/action_view/rendering.rb:30:in `process' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_controller/metal.rb:190:in `dispatch' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_controller/metal.rb:262:in `dispatch' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_dispatch/routing/route_set.rb:50:in `dispatch' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_dispatch/routing/route_set.rb:32:in `serve' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_dispatch/routing/mapper.rb:46:in `serve' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_dispatch/journey/router.rb:39:in `block in serve' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_dispatch/journey/router.rb:26:in `each' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_dispatch/journey/router.rb:26:in `serve' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_dispatch/routing/route_set.rb:727:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  railties (5.0.5) lib/rails/engine.rb:522:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  railties (5.0.5) lib/rails/railtie.rb:193:in `public_send' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  railties (5.0.5) lib/rails/railtie.rb:193:in `method_missing' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:  actionpack (5.0.5) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: actionpack (5.0.5) lib/action_dispatch/routing/mapper.rb:46:in `serve' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: actionpack (5.0.5) lib/action_dispatch/journey/router.rb:39:in `block in serve' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: actionpack (5.0.5) lib/action_dispatch/journey/router.rb:26:in `each' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: actionpack (5.0.5) lib/action_dispatch/journey/router.rb:26:in `serve' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: actionpack (5.0.5) lib/action_dispatch/routing/route_set.rb:727:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: rack (2.0.3) lib/rack/etag.rb:25:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: rack (2.0.3) lib/rack/conditional_get.rb:25:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: rack (2.0.3) lib/rack/head.rb:12:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: rack (2.0.3) lib/rack/session/abstract/id.rb:232:in `context' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: rack (2.0.3) lib/rack/session/abstract/id.rb:226:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: actionpack (5.0.5) lib/action_dispatch/middleware/cookies.rb:613:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: actionpack (5.0.5) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: activesupport (5.0.5) lib/active_support/callbacks.rb:97:in `__run_callbacks__' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: activesupport (5.0.5) lib/active_support/callbacks.rb:750:in `_run_call_callbacks' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: activesupport (5.0.5) lib/active_support/callbacks.rb:90:in `run_callbacks' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: actionpack (5.0.5) lib/action_dispatch/middleware/callbacks.rb:36:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: actionpack (5.0.5) lib/action_dispatch/middleware/remote_ip.rb:79:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: actionpack (5.0.5) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: actionpack (5.0.5) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: railties (5.0.5) lib/rails/rack/logger.rb:36:in `call_app' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: railties (5.0.5) lib/rails/rack/logger.rb:24:in `block in call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: activesupport (5.0.5) lib/active_support/tagged_logging.rb:69:in `block in tagged' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: activesupport (5.0.5) lib/active_support/tagged_logging.rb:26:in `tagged' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: activesupport (5.0.5) lib/active_support/tagged_logging.rb:69:in `tagged' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: railties (5.0.5) lib/rails/rack/logger.rb:24:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: actionpack (5.0.5) lib/action_dispatch/middleware/request_id.rb:24:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: rack (2.0.3) lib/rack/method_override.rb:22:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: rack (2.0.3) lib/rack/runtime.rb:22:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: activesupport (5.0.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: actionpack (5.0.5) lib/action_dispatch/middleware/executor.rb:12:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: actionpack (5.0.5) lib/action_dispatch/middleware/static.rb:136:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: rack (2.0.3) lib/rack/sendfile.rb:111:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: railties (5.0.5) lib/rails/engine.rb:522:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: puma (3.10.0) lib/puma/configuration.rb:225:in `call' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: puma (3.10.0) lib/puma/server.rb:605:in `handle_request' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: puma (3.10.0) lib/puma/server.rb:437:in `process_client' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: puma (3.10.0) lib/puma/server.rb:301:in `block in run' 
Sep 05 12:23:06 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: puma (3.10.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread' 
Sep 05 12:23:24 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: Started GET "/betfair-feed" for 25.0.125.111 at 2017-09-05 16:23:24 +0000 
Sep 05 12:23:24 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest: Processing by PgHero::HomeController#index as HTML 
Sep 05 12:23:24 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:   Parameters: {"database"=>"betfair-feed"} 
Sep 05 12:23:24 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:   Rendering /usr/local/bundle/bundler/gems/pghero-34a116807899views/pg_hero/home/index.html.erb within layouts/pg_hero/application 
Sep 05 12:23:24 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:   Rendered /usr/local/bundle/bundler/gems/pghero-34a116807899views/pg_hero/home/_queries_table.html.erb (1.4ms) 
Sep 05 12:23:24 WAGERING_BATCH_JOBS pg_stats.plucky-considerate-wildebeest:   Rendered /usr/local/bundle/bundler/gems/pghero-34a116807899views/pg_hero/home/index.html.erb within layouts/pg_hero/application (2.3ms) 
```

**Comment by ankane** [comment]
Hey @jontonsoup, thanks for reporting 👍  Should be fixed on master.

**Comment by jontonsoup** [comment]
Nice! Thank you. 

On Tue, Sep 05, 2017 at 8:54 PM Andrew Kane

<
mailto:Andrew Kane <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Hey
https://github.com/jontonsoup
, thanks for reporting

👍

Should be fixed on master.

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/ankane/pghero/issues/142#issuecomment-327367265
, or
