### ISSUE TITLE
Suggestions for multitenancy via schemas options

### ISSUE THREAD

**Issue by ivanovv** [ankane/pghero#144]
First of all, thank you for your hard work, I find pghero to be of great help!

Lately I've joined a company that has used `apartment` gem to implement multitenancy. There are about 90 schemas in the DB now, and some PgHero pages are too slow (or too noisy) to be useful).

So, I have a couple of suggestions:
1.  add a config param to include schema name on the `Space` and `Index Usage`  pages
1. add a config param to limit the number of rows on the `Space` and `Index Usage` pages (it can be a pure `limit N` or show only objects with size greater than X MB)
1. add a config param to disable `Unused Indexes` on the `Overview` page (even for staging with 7 schemas I have 906 indexes there 😂 )

I know you've been working on that on `master`, so maybe it will be possible to implement some of these?

**Comment by ankane** [comment]
Hey @ivanovv, thanks for the suggestions. I think you may be on an old version of PgHero. 1 and 3 shouldn't be issues on the latest version.

**Comment by ivanovv** [comment]
Oh my, I'm running `1.0.4` indeed 😮 
Thanks for pointing that out, will see how `2.0.4` works with so many schemas.

**Comment by ivanovv** [comment]
I've tried `2.0.4` and `2.0.5` with the same result
```
 Completed 500 Internal Server Error in 106046ms (ActiveRecord: 20775.4ms)
```
or 

```
Completed 200 OK in 90147ms (Views: 11.0ms | ActiveRecord: 19297.0ms)
```

500 because of `Rack::Timeout::RequestTimeoutException`


Passenger log:
```
2017-09-18T12:43:25.617Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45] Started GET "/tools/pghero/" for 79.165.99.89 at 2017-09-18 12:43:25 +0000
2017-09-18T12:43:25.617Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=343ms state=active
2017-09-18T12:43:25.617Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45] Processing by PgHero::HomeController#index as HTML
2017-09-18T12:43:25.617Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45]    (2.0ms)  SELECT * FROM pg_stat_statements LIMIT 1 /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:43:25.617Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45]    (1.6ms)  SELECT slot_name, database, active FROM pg_replication_slots /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:43:25.617Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45]    (2.3ms)  SELECT pid, state, application_name AS source, age(NOW(), COALESCE(query_start, xact_start)) AS duration, waiting, query, COALESCE(query_start, xact_start) AS started_at, EXTRACT(EPOCH FROM NOW() - COALESCE(query_start, xact_start)) * 1000.0 AS duration_ms, usename AS user FROM pg_stat_activity WHERE query <> '<insufficient privilege>' AND state <> 'idle' AND pid <> pg_backend_pid() AND datname = current_database() AND NOW() - COALESCE(query_start, xact_start) > interval '60 seconds' ORDER BY COALESCE(query_start, xact_start) DESC /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:43:26.617Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45]    (1.6ms)  SELECT COUNT(*) FROM pg_stat_activity /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:43:26.617Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45]    (4.6ms)  SELECT n.nspname AS schema, c.relname AS table, 2146483648 - GREATEST(AGE(c.relfrozenxid), AGE(t.relfrozenxid)) AS transactions_left FROM pg_class c INNER JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace LEFT JOIN pg_class t ON c.reltoastrelid = t.oid WHERE c.relkind = 'r' AND (2146483648 - GREATEST(AGE(c.relfrozenxid), AGE(t.relfrozenxid))) < 1500000000 ORDER BY 2, 1 /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:43:26.617Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45]    (188.5ms)  SELECT n.nspname AS schema, c.relname AS table, attname AS column, format_type(a.atttypid, a.atttypmod) AS column_type, CASE WHEN format_type(a.atttypid, a.atttypmod) = 'integer' THEN 2147483647::bigint ELSE (pg_sequence_parameters(s.oid)).maximum_value::bigint END AS max_value, s.relname AS sequence FROM pg_catalog.pg_attribute a INNER JOIN pg_catalog.pg_class c ON c.oid = a.attrelid INNER JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace LEFT JOIN pg_catalog.pg_attrdef d ON (a.attrelid, a.attnum) = (d.adrelid, d.adnum) INNER JOIN pg_catalog.pg_class s ON s.relkind = 'S' AND s.relname = regexp_replace(d.adsrc, '^nextval\(''(.*)''\:\:regclass\)$', '\1') WHERE NOT a.attisdropped AND a.attnum > 0 AND d.adsrc LIKE 'nextval%' ORDER BY s.relname ASC /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:43:26.617Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=1000ms state=active
2017-09-18T12:43:27.617Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=2000ms state=active
2017-09-18T12:43:28.618Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=3000ms state=active
2017-09-18T12:43:29.618Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=4000ms state=active
2017-09-18T12:43:30.618Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=5000ms state=active
2017-09-18T12:43:31.618Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=6000ms state=active
2017-09-18T12:43:32.618Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=7000ms state=active
2017-09-18T12:43:33.618Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=8000ms state=active
2017-09-18T12:43:34.618Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=9000ms state=active
2017-09-18T12:43:35.619Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=10000ms state=active
2017-09-18T12:43:36.619Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=11000ms state=active
2017-09-18T12:43:37.619Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=12000ms state=active
2017-09-18T12:43:38.619Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=13000ms state=active
2017-09-18T12:43:39.619Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=14000ms state=active
2017-09-18T12:43:40.619Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=15000ms state=active
2017-09-18T12:43:41.619Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=16000ms state=active
2017-09-18T12:43:42.620Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=17000ms state=active
2017-09-18T12:43:43.620Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=18000ms state=active
2017-09-18T12:44:26.625Z  [ N 2017-09-18 12:44:26.5753 283/T4 age/Cor/CoreMain.cpp:917 ]: Checking whether to disconnect long-running connections for process 1006, application /home/app/backend/public (staging)
2017-09-18T12:44:29.625Z  [ N 2017-09-18 12:44:28.6785 283/T4 age/Cor/CoreMain.cpp:917 ]: Checking whether to disconnect long-running connections for process 1028, application /home/app/backend/public (staging)
2017-09-18T12:44:55.629Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=89420ms state=active
2017-09-18T12:44:55.629Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=89420ms state=timed_out
2017-09-18T12:44:55.629Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45] Could not log "sql.active_record" event. Rack::Timeout::RequestTimeoutException: Request waited 2ms, then ran for longer than 29998ms 
2017-09-18T12:44:56.629Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45]    (1012.2ms)  SELECT schemaname AS schema, t.relname AS table, ix.relname AS name, regexp_replace(pg_get_indexdef(i.indexrelid), '^[^\(]*\((.*)\)$', '\1') AS columns, regexp_replace(pg_get_indexdef(i.indexrelid), '.* USING ([^ ]*) \(.*', '\1') AS using, indisunique AS unique, indisprimary AS primary, indisvalid AS valid, indexprs::text, indpred::text, pg_get_indexdef(i.indexrelid) AS definition FROM pg_index i INNER JOIN pg_class t ON t.oid = i.indrelid INNER JOIN pg_class ix ON ix.oid = i.indexrelid LEFT JOIN pg_stat_user_indexes ui ON ui.indexrelid = i.indexrelid WHERE schemaname IS NOT NULL ORDER BY 1, 2 /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:44:56.629Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45]    (4.4ms)  SELECT COUNT(*) AS count FROM pg_available_extensions WHERE name = 'pg_stat_statements' /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:44:56.629Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45]    (1.5ms)  SELECT COUNT(*) AS count FROM pg_extension WHERE extname = 'pg_stat_statements' /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:44:56.629Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45]   Rendering /usr/local/rvm/gems/ruby-2.3.1/gems/pghero-2.0.4/app/views/pg_hero/home/index.html.erb within layouts/pg_hero/application
2017-09-18T12:44:56.629Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45]   Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/pghero-2.0.4/app/views/pg_hero/home/index.html.erb within layouts/pg_hero/application (4.7ms)
2017-09-18T12:44:56.629Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45] Completed 200 OK in 90147ms (Views: 11.0ms | ActiveRecord: 19297.0ms)
2017-09-18T12:44:56.629Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45]    (1.0ms)  BEGIN /*application:MyApp*/
2017-09-18T12:44:56.629Z  [5f3a9889-a80e-4576-bb7a-be7f16bc9a45]    (1.0ms)  COMMIT /*application:MyApp*/
2017-09-18T12:44:56.629Z  source=rack-timeout id=bf751006887a59836d2f4e6041740a44 wait=2ms timeout=29998ms service=90516ms state=completed
```

Another attempt:
```
2017-09-18T12:49:51.670Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7] Started GET "/tools/pghero/" for 79.165.99.89 at 2017-09-18 12:49:50 +0000
2017-09-18T12:49:51.670Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7] Processing by PgHero::HomeController#index as HTML
2017-09-18T12:49:51.670Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7]    (1.7ms)  SELECT * FROM pg_stat_statements LIMIT 1 /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:49:51.670Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7]    (1.5ms)  SELECT slot_name, database, active FROM pg_replication_slots /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:49:51.670Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7]    (1.8ms)  SELECT pid, state, application_name AS source, age(NOW(), COALESCE(query_start, xact_start)) AS duration, waiting, query, COALESCE(query_start, xact_start) AS started_at, EXTRACT(EPOCH FROM NOW() - COALESCE(query_start, xact_start)) * 1000.0 AS duration_ms, usename AS user FROM pg_stat_activity WHERE query <> '<insufficient privilege>' AND state <> 'idle' AND pid <> pg_backend_pid() AND datname = current_database() AND NOW() - COALESCE(query_start, xact_start) > interval '60 seconds' ORDER BY COALESCE(query_start, xact_start) DESC /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:49:51.670Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7]    (1.5ms)  SELECT COUNT(*) FROM pg_stat_activity /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:49:51.670Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7]    (4.7ms)  SELECT n.nspname AS schema, c.relname AS table, 2146483648 - GREATEST(AGE(c.relfrozenxid), AGE(t.relfrozenxid)) AS transactions_left FROM pg_class c INNER JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace LEFT JOIN pg_class t ON c.reltoastrelid = t.oid WHERE c.relkind = 'r' AND (2146483648 - GREATEST(AGE(c.relfrozenxid), AGE(t.relfrozenxid))) < 1500000000 ORDER BY 2, 1 /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:49:51.670Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7]    (179.4ms)  SELECT n.nspname AS schema, c.relname AS table, attname AS column, format_type(a.atttypid, a.atttypmod) AS column_type, CASE WHEN format_type(a.atttypid, a.atttypmod) = 'integer' THEN 2147483647::bigint ELSE (pg_sequence_parameters(s.oid)).maximum_value::bigint END AS max_value, s.relname AS sequence FROM pg_catalog.pg_attribute a INNER JOIN pg_catalog.pg_class c ON c.oid = a.attrelid INNER JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace LEFT JOIN pg_catalog.pg_attrdef d ON (a.attrelid, a.attnum) = (d.adrelid, d.adnum) INNER JOIN pg_catalog.pg_class s ON s.relkind = 'S' AND s.relname = regexp_replace(d.adsrc, '^nextval\(''(.*)''\:\:regclass\)$', '\1') WHERE NOT a.attisdropped AND a.attnum > 0 AND d.adsrc LIKE 'nextval%' ORDER BY s.relname ASC /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:49:52.670Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=1000ms state=active
2017-09-18T12:49:53.670Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=2000ms state=active
2017-09-18T12:49:54.671Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=3000ms state=active
2017-09-18T12:49:55.671Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=4000ms state=active
2017-09-18T12:49:56.671Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=5000ms state=active
2017-09-18T12:49:57.671Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=6000ms state=active
2017-09-18T12:49:58.671Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=7000ms state=active
2017-09-18T12:49:59.671Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=8000ms state=active
2017-09-18T12:50:00.671Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=9000ms state=active
2017-09-18T12:50:01.672Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=10000ms state=active
2017-09-18T12:50:02.672Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=11000ms state=active
2017-09-18T12:50:03.672Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=12000ms state=active
2017-09-18T12:50:04.672Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=13000ms state=active
2017-09-18T12:50:05.672Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=14000ms state=active
2017-09-18T12:50:06.672Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=15000ms state=active
2017-09-18T12:50:07.672Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=16000ms state=active
2017-09-18T12:50:08.673Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=17000ms state=active
2017-09-18T12:50:09.673Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=18000ms state=active
2017-09-18T12:50:10.673Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=19000ms state=active
2017-09-18T12:51:16.682Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=84928ms state=active
2017-09-18T12:51:16.682Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=84928ms state=timed_out
2017-09-18T12:51:16.683Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7] Could not log "sql.active_record" event. Rack::Timeout::RequestTimeoutException: Request waited 2ms, then ran for longer than 29998ms
2017-09-18T12:51:17.683Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7]    (1015.8ms)  SELECT schemaname AS schema, t.relname AS table, ix.relname AS name, regexp_replace(pg_get_indexdef(i.indexrelid), '^[^\(]*\((.*)\)$', '\1') AS columns, regexp_replace(pg_get_indexdef(i.indexrelid), '.* USING ([^ ]*) \(.*', '\1') AS using, indisunique AS unique, indisprimary AS primary, indisvalid AS valid, indexprs::text, indpred::text, pg_get_indexdef(i.indexrelid) AS definition FROM pg_index i INNER JOIN pg_class t ON t.oid = i.indrelid INNER JOIN pg_class ix ON ix.oid = i.indexrelid LEFT JOIN pg_stat_user_indexes ui ON ui.indexrelid = i.indexrelid WHERE schemaname IS NOT NULL ORDER BY 1, 2 /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:51:17.683Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7]    (4.1ms)  SELECT COUNT(*) AS count FROM pg_available_extensions WHERE name = 'pg_stat_statements' /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:51:17.683Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7]    (1.4ms)  SELECT COUNT(*) AS count FROM pg_extension WHERE extname = 'pg_stat_statements' /*application:MyApp,controller:pg_hero/home,action:index*/
2017-09-18T12:51:17.683Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7]   Rendering /usr/local/rvm/gems/ruby-2.3.1/gems/pghero-2.0.4/app/views/pg_hero/home/index.html.erb within layouts/pg_hero/application
2017-09-18T12:51:17.683Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7]   Rendered /usr/local/rvm/gems/ruby-2.3.1/gems/pghero-2.0.4/app/views/pg_hero/home/index.html.erb within layouts/pg_hero/application (4.5ms)
2017-09-18T12:51:17.683Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7] Completed 200 OK in 86014ms (Views: 9.6ms | ActiveRecord: 19994.5ms)
2017-09-18T12:51:17.683Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7]    (1.2ms)  BEGIN /*application:MyApp*/
2017-09-18T12:51:17.683Z [e345afd7-a2bf-4e11-b38f-67ad2f4f2be7]    (1.1ms)  COMMIT /*application:MyApp*/
2017-09-18T12:51:17.683Z source=rack-timeout id=0d8e13f5683ba23e633734b1ebbb5ae0 wait=2ms timeout=29998ms service=86045ms state=completed
```

the stack trace
```
gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `async_exec': Request waited 720ms, then ran for longer than 29280ms (Rack::Timeout::RequestTimeoutException)
    from gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
    from gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
    from gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
    from gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
    from gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'
    from gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
    from gems/activerecord-5.0.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
    from gems/marginalia-1.4.0/lib/marginalia.rb:62:in `exec_query_with_marginalia'
    from gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:373:in `select'
    from gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'
    from gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
    from gems/pghero-2.0.4/lib/pghero/methods/basic.rb:56:in `select_all'
    from gems/pghero-2.0.4/lib/pghero/methods/indexes.rb:142:in `indexes'
    from gems/pghero-2.0.4/app/controllers/pg_hero/home_controller.rb:47:in `index'
```


I think that is the query that is to get executed:
```sql
SELECT
    schemaname AS schema,
    t.relname AS table,
    ix.relname AS name,
    regexp_replace(pg_get_indexdef(i.indexrelid), '^[^\(]*\((.*)\)$', '\1') AS columns,
    regexp_replace(pg_get_indexdef(i.indexrelid), '.* USING ([^ ]*) \(.*', '\1') AS using,
    indisunique AS unique,
    indisprimary AS primary,
    indisvalid AS valid,
    indexprs::text,
    indpred::text,
    pg_get_indexdef(i.indexrelid) AS definition
  FROM
    pg_index i
  INNER JOIN
    pg_class t ON t.oid = i.indrelid
  INNER JOIN
    pg_class ix ON ix.oid = i.indexrelid
  LEFT JOIN
    pg_stat_user_indexes ui ON ui.indexrelid = i.indexrelid
  WHERE
    schemaname IS NOT NULL
  ORDER BY
    1, 2
```

So I ran it, and it executes successfully
```
(1631 rows)

Time: 569.860 ms
```     


My best guess for the root cause is this - the problem is not with the `indexes` SQL, but with this one
```sql
SELECT 
n.nspname AS schema, 
c.relname AS table, 
attname AS column, 
format_type(a.atttypid, a.atttypmod) AS column_type, 
CASE WHEN format_type(a.atttypid, a.atttypmod) = 'integer' THEN 2147483647::bigint ELSE (pg_sequence_parameters(s.oid)).maximum_value::bigint END AS max_value, 
s.relname AS sequence 
FROM pg_catalog.pg_attribute a 
INNER JOIN pg_catalog.pg_class c ON c.oid = a.attrelid 
INNER JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace 
LEFT JOIN pg_catalog.pg_attrdef d ON (a.attrelid, a.attnum) = (d.adrelid, d.adnum) 
INNER JOIN pg_catalog.pg_class s ON s.relkind = 'S' AND s.relname = regexp_replace(d.adsrc, '^nextval\(''(.*)''\:\:regclass\)$', '\1') 
WHERE NOT a.attisdropped AND a.attnum > 0 AND d.adsrc LIKE 'nextval%' ORDER BY s.relname ASC
```

for my DB it returns `6281 rows` and then I guess it just takes too much time for Ruby to process it, and it gets killed by the `Rack::Timeout::RequestTimeoutException`

**Comment by ankane** [comment]
Hey @ivanovv, from the trace, it looks like it's happening when querying for indexes. Can you set the rack timeout value very high for a bit to try and get it to fully load?

**Comment by ankane** [comment]
Cleaning up stale issues. @ivanovv let me know if you find anything.

**Comment by till** [comment]
@ankane I updated to 2.7.3 just now, I am unable to see schemas at all? Is there anything to enable for this to work?
