### ISSUE TITLE
NoMethodError: undefined method `column_types'

### ISSUE THREAD

**Issue by sobrinho** [ankane/pghero#176]
Hey!

Using Rails 3.2 PgHero is not working.

Root cause:

```
irb(main):006:0> PgHero.databases.values[0].send(:select_one, 'select 1')
   (2.3ms)  select 1
NoMethodError: undefined method `column_types' for [{"?column?"=>"1"}]:Array
        from /app/vendor/bundle/ruby/2.3.0/gems/pghero-2.1.0/lib/pghero/methods/basic.rb:42:in `block (2 levels) in select_all'
        from /app/vendor/bundle/ruby/2.3.0/gems/pghero-2.1.0/lib/pghero/methods/basic.rb:42:in `each'
        from /app/vendor/bundle/ruby/2.3.0/gems/pghero-2.1.0/lib/pghero/methods/basic.rb:42:in `map'
        from /app/vendor/bundle/ruby/2.3.0/gems/pghero-2.1.0/lib/pghero/methods/basic.rb:42:in `block in select_all'
        from /app/vendor/bundle/ruby/2.3.0/gems/pghero-2.1.0/lib/pghero/methods/basic.rb:42:in `map'
        from /app/vendor/bundle/ruby/2.3.0/gems/pghero-2.1.0/lib/pghero/methods/basic.rb:42:in `select_all'
        from /app/vendor/bundle/ruby/2.3.0/gems/pghero-2.1.0/lib/pghero/methods/basic.rb:68:in `select_one'
        from (irb):6
        from /app/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.5/lib/rails/commands/console.rb:47:in `start'
        from /app/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.5/lib/rails/commands/console.rb:8:in `start'
        from /app/vendor/bundle/ruby/2.3.0/gems/railties-3.2.22.5/lib/rails/commands.rb:41:in `<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in `<main>'
```

**Comment by ankane** [comment]
Hey @sobrinho, only 4.2+ Is supported.

**Comment by sobrinho** [comment]
@ankane any reason for that? Would you accept a PR fixing this?

**Comment by ankane** [comment]
@sobrinho Supporting old versions takes time and energy (even just to review and test a PR to add support). I won’t be expanding version support, but feel free to fork and use as needed (a great part of open source).

**Comment by sobrinho** [comment]
@ankane thanks! <3
