### ISSUE TITLE
The home page throws an error while loading

### ISSUE THREAD

**Issue by abhijitiitr** [ankane/pghero#186]
The rails log is shown as below. Apparently an integer is violating the 4 byte integer limit in the table. 
We do have large tables and lots of seq scans, idx scans, tup fetched, returned. Can you suggest a workaround or a fix?

```bash
Started GET "/pghero" for 90.209.163.141 at 2018-02-12 19:29:19 +0000
Processing by PgHero::HomeController#index as HTML
Completed 500 Internal Server Error in 14ms

  RangeError (4181858661 is out of range for ActiveRecord::ConnectionAdapters::PostgreSQL::OID::Integer with limit 4):
  activerecord (4.2.0) lib/active_record/type/integer.rb:41:in `ensure_in_range'
  activerecord (4.2.0) lib/active_record/type/integer.rb:34:in `cast_value'
  activerecord (4.2.0) lib/active_record/type/value.rb:89:in `type_cast'
  activerecord (4.2.0) lib/active_record/type/numeric.rb:15:in `type_cast'
  pghero (2.1.0) lib/pghero/methods/basic.rb:42:in `block (2 levels) in select_all'
  pghero (2.1.0) lib/pghero/methods/basic.rb:42:in `each'
  pghero (2.1.0) lib/pghero/methods/basic.rb:42:in `map'
  pghero (2.1.0) lib/pghero/methods/basic.rb:42:in `block in select_all'
  activerecord (4.2.0) lib/active_record/result.rb:51:in `block in each'
  activerecord (4.2.0) lib/active_record/result.rb:51:in `each'
  activerecord (4.2.0) lib/active_record/result.rb:51:in `each'
  pghero (2.1.0) lib/pghero/methods/basic.rb:42:in `map'
  pghero (2.1.0) lib/pghero/methods/basic.rb:42:in `select_all'
  pghero (2.1.0) lib/pghero/methods/query_stats.rb:43:in `query_stats_readable?'
  pghero (2.1.0) lib/pghero/methods/query_stats.rb:35:in `query_stats_enabled?'
  pghero (2.1.0) app/controllers/pg_hero/home_controller.rb:332:in `set_query_stats_enabled'
  activesupport (4.2.0) lib/active_support/callbacks.rb:427:in `block in make_lambda'
  activesupport (4.2.0) lib/active_support/callbacks.rb:163:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
 
```

**Comment by ankane** [comment]
Hey @abhijitiitr, PgHero is just doing `SELECT * FROM pg_stat_statements LIMIT 1`, so it might be that ActiveRecord is inferring the wrong type. I'd try upgrading Rails to the latest patch version of 4.2 to see if that fixes it.

**Comment by abhijitiitr** [comment]
@ankane Thanks a lot. Updating the version to `4.2.2` fixes the issue.
