### ISSUE TITLE
Working with complex passwords

### ISSUE THREAD

**Issue by Spritekin** [ankane/pghero#190]
Hi,

First, awesome tool! Helps me a lot!

But now, I'm trying to use complex passwords like for example:

DATABASE_URL='postgres://user:({VRy<sD+(Bu2*x_}J4`3^\XY@host:5432/dbname'

DATABASE_URL='postgres://user:<rb1Y%%<]zc?vrTG@host:5432/dbname'

But pghero fails to handle this and always fails like:

```
> docker run -ti   -e DATABASE_URL='postgres://user:({VRy<sD+(Bu2*x_}J4`3^\XY@host:5432/dbname'   -p 8080:8080 ankane/pghero

[7] Puma starting in cluster mode...
[7] * Version 3.11.0 (ruby 2.4.2-p198), codename: Love Song
[7] * Min threads: 1, max threads: 16
[7] * Environment: development
[7] * Process workers: 3
[7] * Preloading application
[7] ! Unable to load application: Bundler::GemRequireError: There was an error while trying to load the gem 'pghero'.
Gem Load Error is: bad URI(is not URI?): postgres://user:({VRy<sD+(Bu2*x_}J4`3^\XY@host:5432/dbname
Backtrace for gem load error is:
/usr/local/lib/ruby/2.4.0/uri/rfc2396_parser.rb:177:in `split'
/usr/local/lib/ruby/2.4.0/uri/rfc2396_parser.rb:212:in `parse'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:38:in `initialize'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:268:in `new'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:268:in `resolve_url_connection'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:256:in `resolve_hash_connection'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:231:in `resolve_connection'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:141:in `resolve'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:161:in `block in resolve_all'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:160:in `each'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:160:in `resolve_all'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:70:in `resolve'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/core.rb:46:in `configurations='
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/core.rb:48:in `block in <module:Core>'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/concern.rb:120:in `class_eval'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/concern.rb:120:in `append_features'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/base.rb:291:in `include'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/base.rb:291:in `<class:Base>'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/base.rb:275:in `<module:ActiveRecord>'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/base.rb:25:in `<top (required)>'
/usr/local/bundle/gems/pghero-2.1.0/lib/pghero/connection.rb:2:in `require'
/usr/local/bundle/gems/pghero-2.1.0/lib/pghero/connection.rb:2:in `<module:PgHero>'
/usr/local/bundle/gems/pghero-2.1.0/lib/pghero/connection.rb:1:in `<top (required)>'
/usr/local/bundle/gems/pghero-2.1.0/lib/pghero.rb:26:in `require'
/usr/local/bundle/gems/pghero-2.1.0/lib/pghero.rb:26:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `each'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `block in require'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `each'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler.rb:114:in `require'
/app/config/application.rb:2:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/app/config/environment.rb:2:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
config.ru:3:in `block in <main>'
/usr/local/bundle/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
/usr/local/bundle/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
config.ru:in `new'
config.ru:in `<main>'
/usr/local/bundle/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
/usr/local/bundle/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
/usr/local/bundle/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
/usr/local/bundle/gems/puma-3.11.0/lib/puma/configuration.rb:318:in `load_rackup'
/usr/local/bundle/gems/puma-3.11.0/lib/puma/configuration.rb:243:in `app'
/usr/local/bundle/gems/puma-3.11.0/lib/puma/runner.rb:138:in `load_and_bind'
/usr/local/bundle/gems/puma-3.11.0/lib/puma/cluster.rb:397:in `run'
/usr/local/bundle/gems/puma-3.11.0/lib/puma/launcher.rb:183:in `run'
/usr/local/bundle/gems/puma-3.11.0/lib/puma/cli.rb:77:in `run'
/usr/local/bundle/gems/puma-3.11.0/bin/puma:10:in `<top (required)>'
/usr/local/bundle/bin/puma:23:in `load'
/usr/local/bundle/bin/puma:23:in `<main>'
Bundler Error Backtrace:
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'pghero'. (Bundler::GemRequireError)
Gem Load Error is: bad URI(is not URI?): postgres://user:({VRy<sD+(Bu2*x_}J4`3^\XY@host:5432/dbname
Backtrace for gem load error is:
/usr/local/lib/ruby/2.4.0/uri/rfc2396_parser.rb:177:in `split'
/usr/local/lib/ruby/2.4.0/uri/rfc2396_parser.rb:212:in `parse'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:38:in `initialize'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:268:in `new'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:268:in `resolve_url_connection'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:256:in `resolve_hash_connection'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:231:in `resolve_connection'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:141:in `resolve'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:161:in `block in resolve_all'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:160:in `each'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_adapters/connection_specification.rb:160:in `resolve_all'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/connection_handling.rb:70:in `resolve'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/core.rb:46:in `configurations='
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/core.rb:48:in `block in <module:Core>'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/concern.rb:120:in `class_eval'
/usr/local/bundle/gems/activesupport-5.1.4/lib/active_support/concern.rb:120:in `append_features'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/base.rb:291:in `include'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/base.rb:291:in `<class:Base>'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/base.rb:275:in `<module:ActiveRecord>'
/usr/local/bundle/gems/activerecord-5.1.4/lib/active_record/base.rb:25:in `<top (required)>'
/usr/local/bundle/gems/pghero-2.1.0/lib/pghero/connection.rb:2:in `require'
/usr/local/bundle/gems/pghero-2.1.0/lib/pghero/connection.rb:2:in `<module:PgHero>'
/usr/local/bundle/gems/pghero-2.1.0/lib/pghero/connection.rb:1:in `<top (required)>'
/usr/local/bundle/gems/pghero-2.1.0/lib/pghero.rb:26:in `require'
/usr/local/bundle/gems/pghero-2.1.0/lib/pghero.rb:26:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `each'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `block in require'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `each'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler.rb:114:in `require'
/app/config/application.rb:2:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/app/config/environment.rb:2:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
config.ru:3:in `block in <main>'
/usr/local/bundle/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
/usr/local/bundle/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
config.ru:in `new'
config.ru:in `<main>'
/usr/local/bundle/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
/usr/local/bundle/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
/usr/local/bundle/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
/usr/local/bundle/gems/puma-3.11.0/lib/puma/configuration.rb:318:in `load_rackup'
/usr/local/bundle/gems/puma-3.11.0/lib/puma/configuration.rb:243:in `app'
/usr/local/bundle/gems/puma-3.11.0/lib/puma/runner.rb:138:in `load_and_bind'
/usr/local/bundle/gems/puma-3.11.0/lib/puma/cluster.rb:397:in `run'
/usr/local/bundle/gems/puma-3.11.0/lib/puma/launcher.rb:183:in `run'
/usr/local/bundle/gems/puma-3.11.0/lib/puma/cli.rb:77:in `run'
/usr/local/bundle/gems/puma-3.11.0/bin/puma:10:in `<top (required)>'
/usr/local/bundle/bin/puma:23:in `load'
/usr/local/bundle/bin/puma:23:in `<main>'
Bundler Error Backtrace:
	from /usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:80:in `block (2 levels) in require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `each'
	from /usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `block in require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `each'
	from /usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/bundler.rb:114:in `require'
	from /app/config/application.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /app/config/environment.rb:2:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from /usr/local/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	from config.ru:3:in `block in <main>'
	from /usr/local/bundle/gems/rack-2.0.3/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/bundle/gems/rack-2.0.3/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /usr/local/bundle/gems/rack-2.0.3/lib/rack/builder.rb:49:in `eval'
	from /usr/local/bundle/gems/rack-2.0.3/lib/rack/builder.rb:49:in `new_from_string'
	from /usr/local/bundle/gems/rack-2.0.3/lib/rack/builder.rb:40:in `parse_file'
	from /usr/local/bundle/gems/puma-3.11.0/lib/puma/configuration.rb:318:in `load_rackup'
	from /usr/local/bundle/gems/puma-3.11.0/lib/puma/configuration.rb:243:in `app'
	from /usr/local/bundle/gems/puma-3.11.0/lib/puma/runner.rb:138:in `load_and_bind'
	from /usr/local/bundle/gems/puma-3.11.0/lib/puma/cluster.rb:397:in `run'
	from /usr/local/bundle/gems/puma-3.11.0/lib/puma/launcher.rb:183:in `run'
	from /usr/local/bundle/gems/puma-3.11.0/lib/puma/cli.rb:77:in `run'
	from /usr/local/bundle/gems/puma-3.11.0/bin/puma:10:in `<top (required)>'
	from /usr/local/bundle/bin/puma:23:in `load'
	from /usr/local/bundle/bin/puma:23:in `<main>'
```

Note it doesn't matter what you pass as a user, host or dbname, you always get that error. This works just fine for normal "simple" passwords with alphanumeric characters and maybe dashes or underscores, but something like this fails.

I'm not really sure how to escape this value. I have tried a few ways but won't work... would you please assist?

Regards,
Guimo

**Comment by ankane** [comment]
Hey @Spritekin, see #100.
