### ISSUE TITLE
Ubuntu 18.04 new installation -- 500 Internal Server Error (port 3001 already used?)

### ISSUE THREAD

**Issue by jflambert** [ankane/pghero#271]
There are a few other closed issues (#154 and #225), but none have clear fix steps and whatever worked for these people didn't work for me. What I needed to do was change ports. I have no idea what's on port 3001, it's a pretty stock Ubuntu 18.04 desktop I'm using.

Package version: 2.2.0-1541030911.fcb4b107.bionic

MYUSER is a "superuser" account.

```
# sudo service pghero status
● pghero.service
   Loaded: loaded (/etc/systemd/system/pghero.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-05-16 09:00:14 EDT; 10min ago
 Main PID: 15691 (sleep)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/pghero.service
           └─15691 /bin/sleep infinity

May 16 09:00:14 XXX systemd[1]: Started pghero.service.

# curl -v http://localhost:3001/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3001 (#0)
> GET / HTTP/1.1
> Host: localhost:3001
> User-Agent: curl/7.58.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 500 Internal Server Error
< Date: Thu, 16 May 2019 13:11:21 GMT
< Server: Apache/2.4.39 (Ubuntu)
< Content-Length: 0
< Connection: close
< Content-Type: text/html; charset=UTF-8
< 
* Closing connection 0

# sudo pghero logs
...
May 16 09:00:19 XXX systemd[1]: Started pghero-web-1.service.
May 16 09:00:20 XXX pghero-web-1.service[15846]: [15846] Puma starting in cluster mode...
May 16 09:00:20 XXX pghero-web-1.service[15846]: [15846] * Version 3.12.0 (ruby 2.5.1-p57), codename: Llamas in Pajamas
May 16 09:00:20 XXX pghero-web-1.service[15846]: [15846] * Min threads: 1, max threads: 16
May 16 09:00:20 XXX pghero-web-1.service[15846]: [15846] * Environment: production
May 16 09:00:20 XXX pghero-web-1.service[15846]: [15846] * Process workers: 3
May 16 09:00:20 XXX pghero-web-1.service[15846]: [15846] * Preloading application
May 16 09:00:21 XXX pghero-web-1.service[15846]: [15846] * Listening on tcp://0.0.0.0:3001
May 16 09:00:21 XXX pghero-web-1.service[15846]: bundler: failed to load command: puma (/opt/pghero/vendor/bundle/ruby/2.5.0/bin/puma)
May 16 09:00:21 XXX pghero-web-1.service[15846]: Errno::EADDRINUSE: Address already in use - bind(2) for "0.0.0.0" port 3001
May 16 09:00:21 XXX pghero-web-1.service[15846]:   /opt/pghero/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/binder.rb:272:in `initialize'
May 16 09:00:21 XXX pghero-web-1.service[15846]:   /opt/pghero/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/binder.rb:272:in `new'
May 16 09:00:21 XXX pghero-web-1.service[15846]:   /opt/pghero/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/binder.rb:272:in `add_tcp_listener'
May 16 09:00:21 XXX pghero-web-1.service[15846]:   /opt/pghero/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/binder.rb:105:in `block in parse'
May 16 09:00:21 XXX pghero-web-1.service[15846]:   /opt/pghero/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/binder.rb:88:in `each'
May 16 09:00:21 XXX pghero-web-1.service[15846]:   /opt/pghero/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/binder.rb:88:in `parse'
May 16 09:00:21 XXX pghero-web-1.service[15846]:   /opt/pghero/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/runner.rb:151:in `load_and_bind'
May 16 09:00:21 XXX pghero-web-1.service[15846]:   /opt/pghero/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/cluster.rb:410:in `run'
May 16 09:00:21 XXX pghero-web-1.service[15846]:   /opt/pghero/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/launcher.rb:184:in `run'
May 16 09:00:21 XXX pghero-web-1.service[15846]:   /opt/pghero/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/cli.rb:78:in `run'
May 16 09:00:21 XXX pghero-web-1.service[15846]:   /opt/pghero/vendor/bundle/ruby/2.5.0/gems/puma-3.12.0/bin/puma:10:in `<top (required)>'
May 16 09:00:21 XXX pghero-web-1.service[15846]:   /opt/pghero/vendor/bundle/ruby/2.5.0/bin/puma:23:in `load'
May 16 09:00:21 XXX pghero-web-1.service[15846]:   /opt/pghero/vendor/bundle/ruby/2.5.0/bin/puma:23:in `<top (required)>'
May 16 09:00:21 XXX systemd[1]: pghero-web-1.service: Main process exited, code=exited, status=1/FAILURE
May 16 09:00:21 XXX systemd[1]: pghero-web-1.service: Failed with result 'exit-code'.
May 16 09:00:21 XXX systemd[1]: pghero-web-1.service: Service hold-off time over, scheduling restart.
May 16 09:00:21 XXX systemd[1]: pghero-web-1.service: Scheduled restart job, restart counter is at 5.
May 16 09:00:21 XXX systemd[1]: Stopped pghero-web-1.service.
May 16 09:00:21 XXX systemd[1]: pghero-web-1.service: Start request repeated too quickly.
May 16 09:00:21 XXX systemd[1]: pghero-web-1.service: Failed with result 'exit-code'.
May 16 09:00:21 XXX systemd[1]: Failed to start pghero-web-1.service.
```

So basically port 3001 was not available, but the service was still "running" successfully. I changed to 3999 (random number) and could log in.

```
# sudo pghero config:set PORT=3999
# sudo service pghero restart
# curl -v http://localhost:3999/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 3999 (#0)
> GET / HTTP/1.1
> Host: localhost:3999
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Referrer-Policy: strict-origin-when-cross-origin
< WWW-Authenticate: Basic realm="Application"
< Content-Type: text/html; charset=utf-8
< Cache-Control: no-cache
< X-Request-Id: 5f1a0d58-aeec-4135-842b-268eaf1bbddb
< X-Runtime: 0.002785
< Transfer-Encoding: chunked
< 
HTTP Basic: Access denied.
* Connection #0 to host localhost left intact
```

I suggest changing the documentation/setup instructions to clearly handle ports problem. Like I said I'm a stock Ubuntu 18.04 desktop so you'd think everyone would have the same problem.

Another problem is that the pghero service status is useless in this case. It'll happily report as running even though the "backend" has failed/stopped.

**Comment by ankane** [comment]
Hey @jflambert, thanks for the suggestion, but I don't think it's common to have a process running on port 3001 and the instructions already include how to set the port.

**Comment by jflambert** [comment]
I understand. Also just worth mentioning again that I basically filed two issues in one: the port/documentation issue, and systemd status not accurately reflecting the pg hero web service failure.

**Comment by jflambert** [comment]
And a little more info, it turns out port 3001 is also used by the Nessus security scanner, which I guess I installed a while ago and even after uninstalling, preserves its claim to port 3001. Now I have to look into purging that. But FYI in case it happens again, Nessus does use port 3001.
