### ISSUE TITLE
Failing to get space and querry stats using the docker version

### ISSUE THREAD

**Issue by philmcc** [ankane/pghero#286]
I have a version of pghero set up built directly on linux but I am trying to get it running through docker.

It runs and I can see the front end but when I try to run the capture space stats or capture query stats jobs, I get an error:

UKM061737B61:~ pmcclarence$ docker run -ti  my-pghero bin/rake pghero:capture_space_stats --trace
** Invoke pghero:capture_space_stats (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute pghero:capture_space_stats
Capturing space stats for db1...
NameError: uninitialized constant PgHero::Connection

Capturing space stats for db2...
NameError: uninitialized constant PgHero::Connection

rake aborted!
NameError: uninitialized constant PgHero::Connection
/usr/local/bundle/bundler/gems/pghero-80960454505d/lib/pghero/database.rb:72:in `connection_model'
/usr/local/bundle/bundler/gems/pghero-80960454505d/lib/pghero/methods/basic.rb:80:in `connection'
/usr/local/bundle/bundler/gems/pghero-80960454505d/lib/pghero/methods/basic.rb:36:in `select_all'
/usr/local/bundle/bundler/gems/pghero-80960454505d/lib/pghero/methods/basic.rb:60:in `select_all_size'
/usr/local/bundle/bundler/gems/pghero-80960454505d/lib/pghero/methods/space.rb:9:in `relation_sizes'
/usr/local/bundle/bundler/gems/pghero-80960454505d/lib/pghero/methods/space.rb:126:in `capture_space_stats'
/usr/local/bundle/bundler/gems/pghero-80960454505d/lib/pghero.rb:129:in `block in capture_space_stats'
/usr/local/bundle/bundler/gems/pghero-80960454505d/lib/pghero.rb:158:in `block in each_database'
/usr/local/bundle/bundler/gems/pghero-80960454505d/lib/pghero.rb:156:in `each'
/usr/local/bundle/bundler/gems/pghero-80960454505d/lib/pghero.rb:156:in `each_database'
/usr/local/bundle/bundler/gems/pghero-80960454505d/lib/pghero.rb:127:in `capture_space_stats'
/usr/local/bundle/bundler/gems/pghero-80960454505d/lib/tasks/pghero.rake:9:in `block (2 levels) in <top (required)>'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:271:in `block in execute'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:271:in `each'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:271:in `execute'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:213:in `block in invoke_with_call_chain'
/usr/local/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:193:in `invoke_with_call_chain'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/task.rb:182:in `invoke'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:160:in `invoke_task'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:116:in `each'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:116:in `block in top_level'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:125:in `run_with_threads'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:110:in `top_level'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:83:in `block in run'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:186:in `standard_exception_handling'
/usr/local/bundle/gems/rake-12.3.1/lib/rake/application.rb:80:in `run'
/usr/local/bundle/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
bin/rake:29:in `load'
bin/rake:29:in `<main>'
Tasks: TOP => pghero:capture_space_stats

I have set up the PGHERO_STATS_DATABASE_URL= when I initially run the container. 
I also set multiple dbs using the pghero.yml file.

Im I doing something wrong or does this way not work>?

**Comment by philmcc** [comment]
I have updated to the latest docker image released and this problem is no longer happening.
