### ISSUE TITLE
Docker image won't run

### ISSUE THREAD

**Issue by mubaidr** [ankane/pghero#304]
When running basic docker image using guide here: https://github.com/ankane/pghero/blob/master/guides/Docker.md#customization--multiple-databases

Following error popup. Why does it needs `config/puma.rb` and where to find it?

```bash
ORS_DB_pghero | /usr/local/bundle/gems/puma-4.3.0/lib/puma/dsl.rb:46:in `read': No such file or directory @ rb_sysopen - config/puma.rb (Errno::ENOENT)
ORS_DB_pghero |         from /usr/local/bundle/gems/puma-4.3.0/lib/puma/dsl.rb:46:in `_load_from'
ORS_DB_pghero |         from /usr/local/bundle/gems/puma-4.3.0/lib/puma/configuration.rb:195:in `block in load'
ORS_DB_pghero |         from /usr/local/bundle/gems/puma-4.3.0/lib/puma/configuration.rb:195:in `each'
ORS_DB_pghero |         from /usr/local/bundle/gems/puma-4.3.0/lib/puma/configuration.rb:195:in `load'
ORS_DB_pghero |         from /usr/local/bundle/gems/puma-4.3.0/lib/puma/launcher.rb:58:in `initialize'
ORS_DB_pghero |         from /usr/local/bundle/gems/puma-4.3.0/lib/puma/cli.rb:71:in `new'
ORS_DB_pghero |         from /usr/local/bundle/gems/puma-4.3.0/lib/puma/cli.rb:71:in `initialize'
ORS_DB_pghero |         from /usr/local/bundle/gems/puma-4.3.0/bin/puma:8:in `new'
ORS_DB_pghero |         from /usr/local/bundle/gems/puma-4.3.0/bin/puma:8:in `<top (required)>'
ORS_DB_pghero |         from /usr/local/bundle/bin/puma:23:in `load'
ORS_DB_pghero |         from /usr/local/bundle/bin/puma:23:in `<main>'
ORS_DB_pghero exited with code 1
```

**Comment by mubaidr** [comment]
Changing the `WORKDIR` in `DockerFile` causes this error to popup. But I believe `config/puma.rb` should be required by absolute path.

**Comment by ankane** [comment]
Hey @mubaidr, thanks for the suggestion! `master` now uses an absolute path. https://github.com/pghero/pghero/commit/1abfb16b88923b4b674274f14c227b728e08b904
