### ISSUE TITLE
500 Error using Kubernetes

### ISSUE THREAD

**Issue by jbaruch76** [ankane/pghero#317]
Trying to get this up and running, currently hitting this error in the logs and not sure where to go from here.
yaml:
```
data:
  pghero.yml: |-
    databases:
      main:
        url: <%= ENV["postgres://postgres:password@postgres-postgresql/db"] %>
```
LOG:
```
[1] Puma starting in cluster mode...
[1] * Version 4.3.3 (ruby 2.7.1-p83), codename: Mysterious Traveller
[1] * Min threads: 1, max threads: 16
[1] * Environment: production
[1] * Process workers: 3
[1] * Preloading application
[1] * Listening on tcp://0.0.0.0:8080
[1] ! WARNING: Detected 1 Thread(s) started in app boot:
[1] ! #<Thread:0x000055ce98f55b10 /usr/local/bundle/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:38 sleep_forever> - /usr/local/bundle/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby/concurrent/atomic/ruby_thread_local_var.rb:40:in `pop'
[1] Use Ctrl-C to stop
[1] - Worker 0 (pid: 7) booted, phase: 0
[1] - Worker 1 (pid: 15) booted, phase: 0
[1] - Worker 2 (pid: 19) booted, phase: 0
Started GET "/" for 65.191.79.126 at 2020-05-21 14:47:27 +0000
Processing by PgHero::HomeController#index as HTML
Completed 500 Internal Server Error in 36ms (ActiveRecord: 0.0ms | Allocations: 7378)
NoMethodError (undefined method `values' for nil:NilClass):
pghero (2.4.2) lib/pghero/methods/basic.rb:67:in `select_one'
pghero (2.4.2) lib/pghero/methods/replication.rb:6:in `replica?'
pghero (2.4.2) app/controllers/pg_hero/home_controller.rb:377:in `set_query_stats_enabled'
activesupport (6.0.2.2) lib/active_support/callbacks.rb:429:in `block in make_lambda'
activesupport (6.0.2.2) lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
actionpack (6.0.2.2) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (6.0.2.2) lib/active_support/callbacks.rb:202:in `block in halting'
activesupport (6.0.2.2) lib/active_support/callbacks.rb:514:in `block in invoke_before'
activesupport (6.0.2.2) lib/active_support/callbacks.rb:514:in `each'
activesupport (6.0.2.2) lib/active_support/callbacks.rb:514:in `invoke_before'
activesupport (6.0.2.2) lib/active_support/callbacks.rb:134:in `run_callbacks'
actionpack (6.0.2.2) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.2.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.2.2) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.2.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.2.2) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.2.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.2.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.2.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.2.2) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.2.2) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.2.2) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (6.0.2.2) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.2.2) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
actionpack (6.0.2.2) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:837:in `call'
railties (6.0.2.2) lib/rails/engine.rb:526:in `call'
railties (6.0.2.2) lib/rails/railtie.rb:190:in `public_send'
railties (6.0.2.2) lib/rails/railtie.rb:190:in `method_missing'
actionpack (6.0.2.2) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (6.0.2.2) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.2.2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.2.2) lib/action_dispatch/routing/route_set.rb:837:in `call'
rack (2.2.2) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.2) lib/rack/etag.rb:27:in `call'
rack (2.2.2) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.2) lib/rack/head.rb:12:in `call'
actionpack (6.0.2.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.2) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.2) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/cookies.rb:648:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.2.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (6.0.2.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.2.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.2.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.2.2) lib/action_dispatch/middleware/host_authorization.rb:77:in `call'
railties (6.0.2.2) lib/rails/engine.rb:526:in `call'
rack (2.2.2) lib/rack/urlmap.rb:74:in `block in call'
rack (2.2.2) lib/rack/urlmap.rb:58:in `each'
rack (2.2.2) lib/rack/urlmap.rb:58:in `call'
puma (4.3.3) lib/puma/configuration.rb:228:in `call'
puma (4.3.3) lib/puma/server.rb:682:in `handle_request'
puma (4.3.3) lib/puma/server.rb:472:in `process_client'
puma (4.3.3) lib/puma/server.rb:328:in `block in run'
puma (4.3.3) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by ankane** [comment]
Hey @jbaruch76, from the error message, it seems like `SELECT pg_is_in_recovery()` is not returning any rows, which is odd. Can you try running that query directly on the database? Also, can you provide more details on the Postgres version and provider?

**Comment by jbaruch76** [comment]
Thanks for the response. I do get back 1 row when running that query with a value of 'f'. Using this docker image: docker.io/bitnami/postgresql:11.7.0-debian-10-r82.

**Comment by ankane** [comment]
Thanks for the additional info. A few follow-up questions:

1. Are you using a connection pooler? The only reference I was able to find about that query returning no rows was [this bug](https://www.pgpool.net/mantisbt/view.php?id=446) from Pgpool-II.
2. Are you using the same connection string as PgHero when `SELECT pg_is_in_recovery()` returns a single row?

**Comment by jbaruch76** [comment]
I do not know the answer to the first question, but this was the response I got from another dev: 
Yes, we use connection pooling, via the python scripts
but not a 'global' for pg, no pgpool

as for 2, I can successfully login from another container using `psql -h postgres-postgresql -U postgres -d db` and login with the password

**Comment by ankane** [comment]
Yeah, think that's it. The url should be:

```yml
url: postgres://postgres:password@postgres-postgresql/db
```

instead of

```yml
url: <%= ENV["postgres://postgres:password@postgres-postgresql/db"] %>
```

The latter is setting an empty url, which is defaulting to a null database adapter, which always returns zero rows.

**Comment by jbaruch76** [comment]
Thank you! That did it, I thought I was following the yaml here https://github.com/ankane/pghero/blob/master/guides/Docker.md . Your help is much appreciated thanks for the app.

**Comment by ankane** [comment]
The config in the instructions expect `DATABASE_URL` to be set as an environment variable, fwiw. Anyways, will try to have it throw a better error in the future.

**Comment by jbaruch76** [comment]
Gotcha, hadn't seen that syntax before. Maybe, as an idea, include those env vars in the kubernetes template? Just in case someone else makes the same mistake. Thanks again.

**Comment by ankane** [comment]
Happy to review a PR for better docs. I haven't used Kubernetes much, but essentially we need to make sure the database URLs are kept secret (like I imagine they are for apps).
