### ISSUE TITLE
Errors when running PgHero.capture_query_stats

### ISSUE THREAD

**Issue by vitobotta** [ankane/pghero#332]
Hi!

I have added the gem and run the migration, but I get this error when running `PgHero.capture_query_stats`:

```
irb(main):001:0> PgHero.capture_query_stats
   (0.7ms)  SELECT current_database() /*pghero*/
NoMethodError: undefined method `cast_value' for nil:NilClass

   (1.8ms)  SELECT current_database() /*pghero*/
NoMethodError: undefined method `cast_value' for nil:NilClass

Traceback (most recent call last):
       16: from pghero (2.7.0) lib/pghero.rb:219:in `each_database'
       15: from pghero (2.7.0) lib/pghero.rb:219:in `each'
       14: from pghero (2.7.0) lib/pghero.rb:221:in `block in each_database'
       13: from pghero (2.7.0) lib/pghero.rb:165:in `block in capture_query_stats'
       12: from pghero (2.7.0) lib/pghero/methods/query_stats.rb:133:in `capture_query_stats'
       11: from pghero (2.7.0) lib/pghero/methods/basic.rb:18:in `database_name'
       10: from pghero (2.7.0) lib/pghero/methods/basic.rb:92:in `select_one'
        9: from pghero (2.7.0) lib/pghero/methods/basic.rb:45:in `select_all'
        8: from pghero (2.7.0) lib/pghero/methods/basic.rb:45:in `map'
        7: from rails (f485a0da293d) activerecord/lib/active_record/result.rb:62:in `each'
        6: from rails (f485a0da293d) activerecord/lib/active_record/result.rb:62:in `each'
        5: from rails (f485a0da293d) activerecord/lib/active_record/result.rb:62:in `block in each'
        4: from pghero (2.7.0) lib/pghero/methods/basic.rb:45:in `block in select_all'
        3: from pghero (2.7.0) lib/pghero/methods/basic.rb:45:in `map'
        2: from pghero (2.7.0) lib/pghero/methods/basic.rb:45:in `each'
        1: from pghero (2.7.0) lib/pghero/methods/basic.rb:45:in `block (2 levels) in select_all'
NoMethodError (undefined method `cast_value' for nil:NilClass)
```

I am looking at the code but I am not sure of what's going on. Thanks in advance for any help :)

**Comment by ankane** [comment]
Hey @vitobotta, it looks like you're on edge Rails, which may have a breaking change (and isn't supported yet).

**Comment by vitobotta** [comment]
Gotcha, thanks.

**Comment by ankane** [comment]
Hey @vitobotta, looks like that method isn't needed in Rails 6+, so should be fixed on master.
