### ISSUE TITLE
Question : Unpacked docker image throws errors on clean query stats

### ISSUE THREAD

**Issue by bheemreddy181** [ankane/pghero#348]
Hi Ankane ,

Need some help for you to understand why unpacked docker image throws the below error while running clean_query_stats using a custom sidekiq worker 

```RuntimeError: NullDB not configured. Require a framework, ex 'nulldb/rails'```

below is my application.rb

```
# frozen_string_literal: true

require 'bundler/setup'
Bundler.require

# silence Ruby 2.7 deprecation warnings
# remove when Rails 6.0.3 released
$VERBOSE = nil

require 'rails'

%w[
  active_record/railtie
  action_controller/railtie
  action_view/railtie
  sprockets/railtie
].each do |railtie|
  require railtie
rescue LoadError
end

ENV['RAILS_APP_VERSION'] = E20::Ops::Revision.new.to_s

unless ENV['DATABASE_URL']
  if File.exist?(PgHero.config_path)
    ENV['DATABASE_URL'] = 'nulldb:///'
  else
    abort 'No DATABASE_URL or config/pghero.yml'
  end
end

require 'dotenv'
Dotenv.overload

module EnovaPGHero
  class Application < Rails::Application
    config.cache_classes = true
    config.eager_load = true
    config.log_level = :info
    config.secret_key_base = ENV['SECRET_KEY_BASE'] || SecureRandom.hex(30)

    config.public_file_server.enabled = ENV['RAILS_SERVE_STATIC_FILES'] != 'disabled'

    config.hosts = nil

    PgHero.show_migrations = ENV['PGHERO_SHOW_MIGRATIONS']
  end
end

```

Tried digging throw the code to see why but wasn't able to figure it out.

**Comment by bheemreddy181** [comment]
We had to upack the docker image so that we can pghero as rails application for deployment - with docker images currently we don't have a good way fo storing secrets so we had to go with this route. 

below is some stack trace for reference 

```
2020-12-09T13:08:07.937Z pid=51675 tid=rev WARN: /Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-nulldb-adapter-0.4.0/lib/nulldb/core.rb:18:in `configuration'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-nulldb-adapter-0.4.0/lib/active_record/connection_adapters/nulldb_adapter/core.rb:146:in `columns'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/schema_cache.rb:76:in `columns'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/schema_cache.rb:82:in `columns_hash'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/model_schema.rb:488:in `load_schema!'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/attributes.rb:247:in `load_schema!'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/attribute_decorators.rb:50:in `load_schema!'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/model_schema.rb:478:in `block in load_schema'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/model_schema.rb:475:in `synchronize'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/model_schema.rb:475:in `load_schema'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/model_schema.rb:362:in `attribute_types'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/model_schema.rb:386:in `type_for_attribute'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/table_metadata.rb:33:in `type'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/relation/predicate_builder.rb:51:in `build'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/relation/predicate_builder.rb:109:in `block in expand_from_hash'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/relation/predicate_builder.rb:68:in `each'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/relation/predicate_builder.rb:68:in `flat_map'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/relation/predicate_builder.rb:68:in `expand_from_hash'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/relation/where_clause_factory.rb:19:in `build'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/relation/query_methods.rb:656:in `where!'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/relation/query_methods.rb:649:in `where'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/querying.rb:21:in `where'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/pghero-2.7.2/lib/pghero/methods/query_stats.rb:168:in `clean_query_stats'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/pghero-2.7.2/lib/pghero.rb:199:in `block in clean_query_stats'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/pghero-2.7.2/lib/pghero.rb:221:in `block in each_database'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/pghero-2.7.2/lib/pghero.rb:219:in `each'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/pghero-2.7.2/lib/pghero.rb:219:in `each_database'
/Users/user/enova_pghero/vendor/bundle/ruby/2.7.0/gems/pghero-2.7.2/lib/pghero.rb:198:in `clean_query_stats'
/Users/user/enova_pghero/app/workers/clean_query_stats_worker.rb:8:in `perform'
```

**Comment by bheemreddy181** [comment]
Working fine after setting the database_url correctly
