### ISSUE TITLE
Crash when setting multiple databases

### ISSUE THREAD

**Issue by athoune** [ankane/pghero#35]
I'm using Debian 8, pghero is a local bundler install with config.ru, Gemfile and Gemlfile.lock stolen from the Docker example.

Everything is fine with one database defined in env DATABASE_URL.

Now, I want multiple databases. I wrote config/pghero.yml as the doc explains.

Here is the stack trace :

```
$ PGHERO_USERNAME=bob PGHERO_PASSWORD=sponge  bundle exec puma -t 8:12 -w 4 -b tcp://1.2.3.4:8000 -e production --preload
[20663] Puma starting in cluster mode...
[20663] * Version 2.9.1 (ruby 2.1.5-p273), codename: Team High Five
[20663] * Min threads: 8, max threads: 12
[20663] * Environment: production
[20663] * Process workers: 4
[20663] * Preloading application
[20663] ! Unable to load application
/var/www/pghero/vendor/ruby/2.1.0/gems/railties-4.1.6/lib/rails/application/configuration.rb:105:in `database_configuration': Cannot load `Rails.application.database_configuration`: (RuntimeError)
Could not load database configuration. No such file -
	from /var/www/pghero/vendor/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/railtie.rb:128:in `block (2 levels) in <class:Railtie>'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:27:in `each'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/activesupport-4.1.6/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/activerecord-4.1.6/lib/active_record/railtie.rb:118:in `block in <class:Railtie>'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/railties-4.1.6/lib/rails/initializable.rb:30:in `run'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/railties-4.1.6/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /usr/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/2.1.0/tsort.rb:345:in `each'


	from /usr/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /usr/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /usr/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /usr/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/railties-4.1.6/lib/rails/initializable.rb:54:in `run_initializers'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/railties-4.1.6/lib/rails/application.rb:300:in `initialize!'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/railties-4.1.6/lib/rails/railtie.rb:194:in `public_send'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/railties-4.1.6/lib/rails/railtie.rb:194:in `method_missing'
	from config.ru:18:in `block in <main>'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `eval'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:49:in `new_from_string'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/rack-1.5.2/lib/rack/builder.rb:40:in `parse_file'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/puma-2.9.1/lib/puma/configuration.rb:96:in `app'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/puma-2.9.1/lib/puma/runner.rb:113:in `load_and_bind'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/puma-2.9.1/lib/puma/cluster.rb:283:in `run'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/puma-2.9.1/lib/puma/cli.rb:499:in `run'
	from /var/www/pghero/vendor/ruby/2.1.0/gems/puma-2.9.1/bin/puma:10:in `<top (required)>'
	from /var/www/pghero/vendor/ruby/2.1.0/bin/puma:23:in `load'
	from /var/www/pghero/vendor/ruby/2.1.0/bin/puma:23:in `<main>'
```

**Comment by athoune** [comment]
Ok, you need your own database, when you want to use multiple databases.

**Comment by jontonsoup** [comment]
@athoune What do you mean by "You need your own database" I am getting this error also.
