### ISSUE TITLE
Missing ld-linux-x86-64.so.2 file while loading GCP system stats

### ISSUE THREAD

**Issue by Yinabled** [ankane/pghero#352]
When loading system stats via the GCP database integration, PgHero (specifically, the gRPC gem within google-cloud-monitoring-v3) seems to try to access a file which does not exist. Relevant stacktrace:
```
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero Error LoadError (Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/local/bundle/gems/grpc-1.32.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so) - /usr/local/bundle/gems/grpc-1.32.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so):
  
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero grpc-1.32.0-x86_64 (linux) src/ruby/lib/grpc/grpc.rb:20:in `require'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero grpc-1.32.0-x86_64 (linux) src/ruby/lib/grpc/grpc.rb:20:in `<top (required)>'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero grpc-1.32.0-x86_64 (linux) src/ruby/lib/grpc.rb:19:in `require_relative'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero grpc-1.32.0-x86_64 (linux) src/ruby/lib/grpc.rb:19:in `<top (required)>'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero gapic-common (0.3.4) lib/gapic/grpc.rb:15:in `require'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero gapic-common (0.3.4) lib/gapic/grpc.rb:15:in `<top (required)>'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero google-cloud-monitoring-v3 (0.1.4) lib/google/cloud/monitoring/v3/metric_service/client.rb:171:in `require'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero google-cloud-monitoring-v3 (0.1.4) lib/google/cloud/monitoring/v3/metric_service/client.rb:171:in `initialize'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero pghero (2.7.3) lib/pghero/methods/system.rb:158:in `new'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero pghero (2.7.3) lib/pghero/methods/system.rb:158:in `gcp_stats'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero pghero (2.7.3) lib/pghero/methods/system.rb:244:in `system_stats'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero pghero (2.7.3) lib/pghero/methods/system.rb:32:in `read_iops_stats'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero pghero (2.7.3) app/controllers/pg_hero/home_controller.rb:242:in `load_stats'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/abstract_controller/base.rb:195:in `process_action'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero activesupport (6.0.3.4) lib/active_support/callbacks.rb:135:in `run_callbacks'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_controller/metal/rescue.rb:22:in `process_action'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `block in instrument'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero activesupport (6.0.3.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero activesupport (6.0.3.4) lib/active_support/notifications.rb:180:in `instrument'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero activerecord (6.0.3.4) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/abstract_controller/base.rb:136:in `process'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionview (6.0.3.4) lib/action_view/rendering.rb:39:in `process'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_controller/metal.rb:190:in `dispatch'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_controller/metal.rb:254:in `dispatch'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:33:in `serve'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/routing/mapper.rb:48:in `serve'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:49:in `block in serve'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `each'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `serve'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero railties (6.0.3.4) lib/rails/engine.rb:527:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero railties (6.0.3.4) lib/rails/railtie.rb:190:in `public_send'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero railties (6.0.3.4) lib/rails/railtie.rb:190:in `method_missing'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/routing/mapper.rb:48:in `serve'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:49:in `block in serve'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `each'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/journey/router.rb:32:in `serve'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/routing/route_set.rb:834:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero rack (2.2.3) lib/rack/etag.rb:27:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero rack (2.2.3) lib/rack/head.rb:12:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/middleware/cookies.rb:648:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero activesupport (6.0.3.4) lib/active_support/callbacks.rb:101:in `run_callbacks'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero railties (6.0.3.4) lib/rails/rack/logger.rb:37:in `call_app'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `block in call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `block in tagged'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:28:in `tagged'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero activesupport (6.0.3.4) lib/active_support/tagged_logging.rb:80:in `tagged'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero railties (6.0.3.4) lib/rails/rack/logger.rb:26:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/middleware/request_id.rb:27:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero rack (2.2.3) lib/rack/method_override.rb:24:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero rack (2.2.3) lib/rack/runtime.rb:22:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero activesupport (6.0.3.4) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/middleware/executor.rb:14:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/middleware/static.rb:126:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero actionpack (6.0.3.4) lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero railties (6.0.3.4) lib/rails/engine.rb:527:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero rack (2.2.3) lib/rack/urlmap.rb:74:in `block in call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero rack (2.2.3) lib/rack/urlmap.rb:58:in `each'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero rack (2.2.3) lib/rack/urlmap.rb:58:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero puma (5.0.4) lib/puma/configuration.rb:239:in `call'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero puma (5.0.4) lib/puma/request.rb:76:in `block in handle_request'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero puma (5.0.4) lib/puma/thread_pool.rb:337:in `with_force_shutdown'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero puma (5.0.4) lib/puma/request.rb:75:in `handle_request'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero puma (5.0.4) lib/puma/server.rb:430:in `process_client'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero puma (5.0.4) lib/puma/thread_pool.rb:145:in `block in spawn_thread'
Jan 13 00:17:52 pghero-c9798b9f5-slc7j pghero Error Completed 500 Internal Server Error in 179ms (ActiveRecord: 0.0ms | Allocations: 79999)
```

For context, I'm running PgHero by running `puma -C config/puma.rb` within the latest PgHero parent image. Our database is on PostgreSQL 9.6.

**Comment by ankane** [comment]
Hey @Yinabled, thanks for reporting! It looks like the Docker image was missing `gcompat`. I just pushed a new image to `pghero:latest` with a fix (https://github.com/pghero/pghero/commit/69d919f53c97e6a2c163246ca36d7fb155bad3b4).

Note to future self: Tried `libc-compat`, but it places `ld-linux-x86-64.so.2` into `/lib64` instead of `/lib`, which isn't in the load path.

**Comment by Yinabled** [comment]
Wonderful - thanks @ankane!
