### ISSUE TITLE
Yet one code 500 error

### ISSUE THREAD

**Issue by hgfdd** [ankane/pghero#356]
Hi, in Centos 7 with PgHero 2.7.3 i am receiving the following error:

```
Started GET "/aspat-beta/" for 127.0.0.1 at 2021-02-01 10:38:44 +0000
Processing by PgHero::HomeController#index as HTML
  Parameters: {"database"=>"aspat-beta"}
Completed 500 Internal Server Error in 34ms (ActiveRecord: 24.7ms | Allocations: 6922)

ArgumentError (comparison of NilClass with String failed):

pghero (2.7.3) lib/pghero/methods/sequences.rb:50:in `sort_by'
pghero (2.7.3) lib/pghero/methods/sequences.rb:50:in `sequences'
pghero (2.7.3) app/controllers/pg_hero/home_controller.rb:48:in `index'
actionpack (6.0.3.4) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (6.0.3.4) lib/abstract_controller/base.rb:195:in `process_action'
actionpack (6.0.3.4) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (6.0.3.4) lib/active_support/callbacks.rb:135:in `run_callbacks'
actionpack (6.0.3.4) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.3.4) lib/action_controller/metal/rescue.rb:22:in `process_action'

```

Thanks in advance!

**Comment by ankane** [comment]
Hey @hgfdd, thanks for reporting! Fixed in the commit above and will push a new release shortly. I'd be curious to see which sequence PgHero is unable to parse after you upgrade - you should be able to find it by clicking on the "unreadable sequences" text.
