### ISSUE TITLE
issues with PgQuery 2.0.1 

### ISSUE THREAD

**Issue by raivil** [ankane/pghero#370]
Latest version (`2.8.0`) fails when upgrading PgQuery from `1.3.0` to `2.0.1`.
Details:
```
Error class: NoMethodError
Transaction name: pg_hero/home#index
Error Message
undefined method `size' for #<PgQuery::ParseResult:0x00007f7e64bcecf8>
```
Stack
```
…ent/vendor/bundle/ruby/2.7.0/gems/pghero-2.8.0/lib/pghero/methods/suggested_indexes.rb:204:in `method_missing'
…ent/vendor/bundle/ruby/2.7.0/gems/pghero-2.8.0/lib/pghero/methods/suggested_indexes.rb:204:in `best_index_structure'
…ent/vendor/bundle/ruby/2.7.0/gems/pghero-2.8.0/lib/pghero/methods/suggested_indexes.rb:99:in `block in best_index_helper'
…ent/vendor/bundle/ruby/2.7.0/gems/pghero-2.8.0/lib/pghero/methods/suggested_indexes.rb:98:in `each'
…ent/vendor/bundle/ruby/2.7.0/gems/pghero-2.8.0/lib/pghero/methods/suggested_indexes.rb:98:in `best_index_helper'
…ent/vendor/bundle/ruby/2.7.0/gems/pghero-2.8.0/lib/pghero/methods/suggested_indexes.rb:17:in `suggested_indexes_by_query'
```

**Comment by marckohlbrugge** [comment]
`pg_query`'s [changelog](https://github.com/pganalyze/pg_query/blob/main/CHANGELOG.md) includes the following:

```
2.0.0 2021-03-18

[…]
Update to libpg_query v2, and new Protobuf-based format
WARNING: This is a breaking change if you are directly interacting with the parsetree (helpers like table and such still work the same way)
[…]
```

It looks like PgHero directly accesses the `tree`:

https://github.com/ankane/pghero/blob/83c4edd1a7123c55862ffbfa831c58814b75fc20/lib/pghero/methods/suggested_indexes.rb#L199-L211

So that's probably the part that needs to be modified to work with the latest `pg_query` version.

**Comment by ankane** [comment]
Thanks for reporting @raivil and looking into it @marckohlbrugge. Should be fixed in the commit above. Will push a new release in the next day or two.
