### ISSUE TITLE
clean_query_stats fails

### ISSUE THREAD

**Issue by lanrat** [ankane/pghero#430]
Running the following for `pghero:clean_query_stats` fails with the following stack-trace & error: 

```bash
$ docker exec -it pghero rake pghero:clean_query_stats
rake aborted!
LoadError: cannot load such file -- /app/db/schema.rb
/usr/local/bundle/gems/activerecord-nulldb-adapter-0.8.0/lib/active_record/connection_adapters/nulldb_adapter/core.rb:143:in `load'
/usr/local/bundle/gems/activerecord-nulldb-adapter-0.8.0/lib/active_record/connection_adapters/nulldb_adapter/core.rb:143:in `columns'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/connection_adapters/schema_cache.rb:117:in `block in columns'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/connection_adapters/schema_cache.rb:116:in `fetch'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/connection_adapters/schema_cache.rb:116:in `columns'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/connection_adapters/schema_cache.rb:125:in `block in columns_hash'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/connection_adapters/schema_cache.rb:124:in `fetch'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/connection_adapters/schema_cache.rb:124:in `columns_hash'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/model_schema.rb:580:in `load_schema!'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/attributes.rb:264:in `load_schema!'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/encryption/encryptable_record.rb:122:in `load_schema!'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/model_schema.rb:566:in `block in load_schema'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/model_schema.rb:563:in `synchronize'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/model_schema.rb:563:in `load_schema'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/model_schema.rb:429:in `attribute_types'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/model_schema.rb:455:in `type_for_attribute'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/type_caster/map.rb:16:in `type_for_attribute'
/usr/local/bundle/gems/activerecord-7.0.4/lib/arel/table.rb:107:in `type_for_attribute'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/table_metadata.rb:18:in `type'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/relation/predicate_builder.rb:59:in `build'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/relation/predicate_builder.rb:54:in `[]'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/relation/predicate_builder.rb:126:in `block in expand_from_hash'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/relation/predicate_builder.rb:79:in `each'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/relation/predicate_builder.rb:79:in `flat_map'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/relation/predicate_builder.rb:79:in `expand_from_hash'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/relation/predicate_builder.rb:25:in `build_from_hash'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/relation/query_methods.rb:1313:in `build_where_clause'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/relation/query_methods.rb:756:in `where!'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/relation/query_methods.rb:751:in `where'
/usr/local/bundle/gems/activerecord-7.0.4/lib/active_record/querying.rb:22:in `where'
/usr/local/bundle/gems/pghero-3.0.1/lib/pghero/methods/query_stats.rb:166:in `clean_query_stats'
/usr/local/bundle/gems/pghero-3.0.1/lib/pghero.rb:217:in `block in clean_query_stats'
/usr/local/bundle/gems/pghero-3.0.1/lib/pghero.rb:252:in `block in each_database'
/usr/local/bundle/gems/pghero-3.0.1/lib/pghero.rb:250:in `each'
/usr/local/bundle/gems/pghero-3.0.1/lib/pghero.rb:250:in `each_database'
/usr/local/bundle/gems/pghero-3.0.1/lib/pghero.rb:216:in `clean_query_stats'
/usr/local/bundle/gems/pghero-3.0.1/lib/tasks/pghero.rake:25:in `block (2 levels) in <top (required)>'
Tasks: TOP => pghero:clean_query_stats
(See full trace by running task with --trace)
```

I did a quick look and only found `schema.rb` [here](https://github.com/ankane/pghero/blob/master/test/internal/db/schema.rb) which appears to only be used for testing?

**Comment by ankane** [comment]
Hey @lanrat, it looks like the stats database URL isn't set. You'll either need to pass `-e DATABASE_URL=...` or set the URL in `pghero.yml`.

**Comment by lanrat** [comment]
@ankane I do have my database urls set in `pghero.yml`. Here is what mine looks like:

```yml
databases:
  admin:
    url: "postgres://USERA:PASS@HOSTNAME_A/DB_ADMIN"

  bar:
    url: "postgres://USERB:PASS@HOSTNAME_B/DB_BAR"
    capture_query_stats: admin

  foo:
    url: "postgres://USERC:PASS@HOSTNAME_C/DB_FOO"
    capture_query_stats: admin
```

Is this the correct syntax?

**Comment by ankane** [comment]
Yes, but you'll need to tell it where the query stats are stored - either with `-e DATABASE_URL=...` (like the example in the docs) or with a top-level `stats_database_url` key in `pghero.yml`.

**Comment by lanrat** [comment]
What is the purpose of the `capture_query_stats` field then?

How do you tell what database to put the stats in? if `stats_database_url` is global?
