### ISSUE TITLE
Rails 7.1 compatibility

### ISSUE THREAD

**Issue by bforma** [ankane/pghero#456]
We've upgraded our app to Rails 7.1-alpha and when we run the `bin/rails credentials:show --environment development` command we get the following error, likely related to pghero:

```ruby
/Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-403e4e5b5639/activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb:242:in `retrieve_connection': No connection pool for 'ActiveRecord::Base' found. (ActiveRecord::ConnectionNotEstablished)
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-403e4e5b5639/activerecord/lib/active_record/connection_handling.rb:288:in `retrieve_connection'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-403e4e5b5639/activerecord/lib/active_record/connection_handling.rb:255:in `connection'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pghero-3.1.0/lib/pghero.rb:239:in `connection_config'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pghero-3.1.0/lib/pghero.rb:152:in `default_config'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pghero-3.1.0/lib/pghero.rb:109:in `config'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/pghero-3.1.0/lib/pghero/engine.rb:23:in `block in <class:Engine>'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-403e4e5b5639/railties/lib/rails/initializable.rb:32:in `instance_exec'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-403e4e5b5639/railties/lib/rails/initializable.rb:32:in `run'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-403e4e5b5639/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:347:in `each'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:347:in `call'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-403e4e5b5639/railties/lib/rails/initializable.rb:60:in `run_initializers'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-403e4e5b5639/railties/lib/rails/application.rb:420:in `initialize!'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-403e4e5b5639/railties/lib/rails/command/actions.rb:27:in `load_environment_config!'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-403e4e5b5639/railties/lib/rails/commands/credentials/credentials_command.rb:36:in `show'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-403e4e5b5639/railties/lib/rails/command/base.rb:179:in `invoke_command'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-403e4e5b5639/railties/lib/rails/command/base.rb:74:in `perform'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-403e4e5b5639/railties/lib/rails/command.rb:71:in `block in invoke'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-403e4e5b5639/railties/lib/rails/command.rb:149:in `with_argv'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-403e4e5b5639/railties/lib/rails/command.rb:69:in `invoke'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/bundler/gems/rails-403e4e5b5639/railties/lib/rails/commands.rb:18:in `<main>'
	from <internal:/Users/someuser/.rbenv/versions/3.2.1/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/someuser/.rbenv/versions/3.2.1/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/someuser/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from bin/rails:5:in `<main>'
```

**Rails version**: 7.1-alpha
**Ruby version**: 3.2.1
**Pghero version**: 3.1.0

Also tried upgrading to pghero latest (3.3.3), but that doesn't solve the issue.

We don't get this error when running `rails s` or `rails c`.

**Comment by ankane** [comment]
Hi @bforma, thanks for reporting, but Rails 7.1 isn't supported yet.

**Comment by bforma** [comment]
Hi @ankane, thanks for the update. Any idea when support for Rails 7.1 is planned?

**Comment by ankane** [comment]
When Rails 7.1 is released

**Comment by ankane** [comment]
Fixed in the commit above
