### ISSUE TITLE
PgHero doesn't use the Rails connection pool, gets whacked by PgBouncer

### ISSUE THREAD

**Issue by sudhirj** [ankane/pghero#56]
I'm not sure how connection pooling happens inside PgHero, but it doesn't seem to survive for very long when running behind PgBouncer. Ironic, yes. 

Is there an internal pool being used for connections? I'm mounting it on a rails app and the rest of the app works fine, so I'm guessing PgHero is doing its own thing with regards to connection pooling. PgHero stops being able to use connections after a few hours, and works again only after a restart.

**Comment by sudhirj** [comment]
PgBouncer is running in transaction mode, if that helps.

**Comment by ankane** [comment]
What error are you seeing? We've been running PgHero behind a bouncer (in transaction mode) for around a year without issues.

**Comment by sudhirj** [comment]
Will double check - but it seems like PgHero gives up when it receives a too many connections error from pgbouncer, even if connections are available a second later. Like the connection error is being cached in some way.

**Comment by sudhirj** [comment]
Not sure it'll help, but here's a stacktrace. #
```
PG::ConnectionBad (ERROR:  no more connections allowed (max_client_conn)
):
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `initialize'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `new'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:655:in `connect'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
  /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
  /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_handling.rb:87:in `connection'
  vendor/bundle/ruby/2.3.0/gems/pghero-1.2.2/lib/pghero.rb:1245:in `connection'
  vendor/bundle/ruby/2.3.0/gems/pghero-1.2.2/lib/pghero.rb:1233:in `select_all'
  vendor/bundle/ruby/2.3.0/gems/pghero-1.2.2/lib/pghero.rb:489:in `query_stats_enabled?'
  vendor/bundle/ruby/2.3.0/gems/pghero-1.2.2/app/controllers/pg_hero/home_controller.rb:199:in `set_query_stats_enabled'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:432:in `block in make_lambda'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:164:in `block in halting'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `block in call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `each'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:504:in `call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
  vendor/bundle/ruby/2.3.0/gems/pghero-1.2.2/app/controllers/pg_hero/home_controller.rb:190:in `set_database'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:432:in `block in make_lambda'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:312:in `block in halting'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:497:in `block in around'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/abstract_controller/base.rb:137:in `process'
  vendor/bundle/ruby/2.3.0/gems/actionview-4.2.4/lib/action_view/rendering.rb:30:in `process'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal.rb:196:in `dispatch'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_controller/metal.rb:237:in `block in action'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:45:in `serve'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:49:in `serve'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `each'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:821:in `call'
  vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/railtie.rb:194:in `public_send'
  vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/railtie.rb:194:in `method_missing'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/mapper.rb:51:in `serve'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `each'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:821:in `call'
  vendor/bundle/ruby/2.3.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
  vendor/bundle/ruby/2.3.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
  vendor/bundle/ruby/2.3.0/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/flash.rb:260:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/cookies.rb:560:in `call'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
  vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/static.rb:116:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
  vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/ssl.rb:24:in `call'
  vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/engine.rb:518:in `call'
  vendor/bundle/ruby/2.3.0/gems/railties-4.2.4/lib/rails/application.rb:165:in `call'
  vendor/bundle/ruby/2.3.0/gems/rack-1.6.4/lib/rack/deflater.rb:35:in `call'
  vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/configuration.rb:227:in `call'
  vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/server.rb:561:in `handle_request'
  vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/server.rb:406:in `process_client'
  vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/server.rb:271:in `block in run'
  vendor/bundle/ruby/2.3.0/gems/puma-3.1.0/lib/puma/thread_pool.rb:111:in `block in spawn_thread'
```

**Comment by ankane** [comment]
This is an error from the bouncer. Try increasing `max_client_conn` or reducing your connections.
