### ISSUE TITLE
Add support for Postgres 9.6

### ISSUE THREAD

**Issue by lpfeup** [ankane/pghero#79]
Accessing the interface currently fails for Postgres 9.6:
``` sql
PG::UndefinedColumn: ERROR: column "waiting" does not exist LINE 1: ...me AS source, age(now(), xact_start) AS duration, waiting, q... ^ : SELECT pid, state, application_name AS source, age(now(), xact_start) AS duration, waiting, query, xact_start AS started_at FROM pg_stat_activity WHERE query <> '<insufficient privilege>' AND state <> 'idle' AND pid <> pg_backend_pid() AND now() - query_start > interval '60 seconds' ORDER BY query_start DESC
```

It seems the column <code>waiting</code> has been removed from <code>pg_stat_activity</code>: https://www.postgresql.org/docs/9.6/static/monitoring-stats.html#PG-STAT-ACTIVITY-VIEW

EDIT: I ran it from Docker: https://github.com/pghero/pghero (v1.4.1)

**Comment by fake-name** [comment]
I'm seeing this error too. Plain install on Ubuntu 16.04, pg is 9.6beta4.

**Comment by ankane** [comment]
Added on master. Will push a release this weekend.

**Comment by fake-name** [comment]
This appears to not be fixed.

With 1.5.2:

```
Oct  2 08:21:35 pghero pghero-web-1.service[497]: [497] Puma starting in cluster mode...
Oct  2 08:21:35 pghero pghero-web-1.service[497]: [497] * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
Oct  2 08:21:35 pghero pghero-web-1.service[497]: [497] * Min threads: 1, max threads: 16
Oct  2 08:21:35 pghero pghero-web-1.service[497]: [497] * Environment: production
Oct  2 08:21:35 pghero pghero-web-1.service[497]: [497] * Process workers: 3
Oct  2 08:21:35 pghero pghero-web-1.service[497]: [497] * Preloading application
Oct  2 08:21:39 pghero pghero-web-1.service[497]: [497] * Listening on tcp://0.0.0.0:6000
Oct  2 08:21:39 pghero pghero-web-1.service[497]: [497] Use Ctrl-C to stop
Oct  2 08:21:39 pghero pghero-web-1.service[497]: [497] - Worker 0 (pid: 612) booted, phase: 0
Oct  2 08:21:39 pghero pghero-web-1.service[497]: [497] - Worker 1 (pid: 622) booted, phase: 0
Oct  2 08:21:39 pghero pghero-web-1.service[497]: [497] - Worker 2 (pid: 632) booted, phase: 0
Oct  2 08:22:52 pghero pghero-web-1.service[497]: Started GET "/" for 10.1.1.4 at 2016-10-02 08:22:52 +0000
Oct  2 08:22:52 pghero pghero-web-1.service[497]: Processing by PgHero::HomeController#index as HTML
Oct  2 08:22:52 pghero pghero-web-1.service[497]: Completed 500 Internal Server Error in 35ms (ActiveRecord: 0.0ms)
Oct  2 08:22:52 pghero pghero-web-1.service[497]:
Oct  2 08:22:52 pghero pghero-web-1.service[497]: ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column "waiting" does not exist
Oct  2 08:22:52 pghero pghero-web-1.service[497]: LINE 1: ...me AS source, age(now(), xact_start) AS duration, waiting, q...
Oct  2 08:22:52 pghero pghero-web-1.service[497]:                                                              ^
Oct  2 08:22:52 pghero pghero-web-1.service[497]: : SELECT pid, state, application_name AS source, age(now(), xact_start) AS duration, waiting, query, xact_start AS started_at, usename AS user FROM pg_stat_activity WHERE query <> '<insufficient privilege>' AND state <> 'idle' AND pid <> pg_backend_pid() AND now() - query_start > interval '60 seconds' AND datname = current_database() ORDER BY query_start DESC):
Oct  2 08:22:52 pghero pghero-web-1.service[497]:
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `async_exec'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:566:in `block in log'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract_adapter.rb:560:in `log'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `exec_no_cache'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:103:in `exec_query'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:373:in `select'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/pghero-1.5.1/lib/pghero/methods/basic.rb:44:in `select_all'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/pghero-1.5.1/lib/pghero/methods/queries.rb:28:in `long_running_queries'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/pghero-1.5.1/app/controllers/pg_hero/home_controller.rb:21:in `index'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/base.rb:188:in `process_action'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:126:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/rescue.rb:20:in `process_action'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `instrument'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.0.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/abstract_controller/base.rb:126:in `process'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionview-5.0.0.1/lib/action_view/rendering.rb:30:in `process'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal.rb:190:in `dispatch'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_controller/metal.rb:262:in `dispatch'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:32:in `serve'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:46:in `serve'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:39:in `block in serve'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:26:in `each'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:26:in `serve'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:725:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:522:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:193:in `public_send'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie.rb:193:in `method_missing'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/mapper.rb:46:in `serve'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:39:in `block in serve'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:26:in `each'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:26:in `serve'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:725:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/conditional_get.rb:25:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/cookies.rb:613:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:36:in `call_app'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `block in call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `block in tagged'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `tagged'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/request_id.rb:24:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.0.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/static.rb:136:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/engine.rb:522:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
Oct  2 08:22:52 pghero pghero-web-1.service[497]: vendor/bundle/ruby/2.3.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'

```
