### ISSUE TITLE
Installation fails on Ubuntu 14.04.5 Server

### ISSUE THREAD

**Issue by tmitchell** [ankane/pghero#83]
Followed instructions from Linux guide.  Apt package appears to install correctly and after configuration and `pghero scale web=1` I see a puma instance running.  However nothing is bound to 6000.  Contents of error log follow:

```
root@host:~# tail -35 /var/log/pghero/web-1.log
[2439] Puma starting in cluster mode...
[2439] * Version 3.4.0 (ruby 2.0.0-p648), codename: Owl Bowl Brawl
[2439] * Min threads: 1, max threads: 16
[2439] * Environment: production
[2439] * Process workers: 3
[2439] * Preloading application
[2439] ! Unable to load application: Bundler::GemRequireError: There was an error while trying to load the gem 'pghero'.
/opt/pghero/vendor/bundle/ruby/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'pghero'. (Bundler::GemRequireError)
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
        from /opt/pghero/config/application.rb:2:in `<top (required)>'
        from /opt/pghero/config/environment.rb:2:in `require'
        from /opt/pghero/config/environment.rb:2:in `<top (required)>'
        from config.ru:3:in `require'
        from config.ru:3:in `block in <main>'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
        from config.ru:in `new'
        from config.ru:in `<main>'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/puma-3.4.0/lib/puma/configuration.rb:313:in `load_rackup'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/puma-3.4.0/lib/puma/configuration.rb:242:in `app'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/puma-3.4.0/lib/puma/runner.rb:123:in `load_and_bind'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/puma-3.4.0/lib/puma/cluster.rb:370:in `run'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/puma-3.4.0/lib/puma/launcher.rb:172:in `run'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/puma-3.4.0/lib/puma/cli.rb:74:in `run'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/gems/puma-3.4.0/bin/puma:10:in `<top (required)>'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/bin/puma:23:in `load'
        from /opt/pghero/vendor/bundle/ruby/2.0.0/bin/puma:23:in `<main>'
```

**Comment by tmitchell** [comment]
Manual install of the pghero gem yields:

```
root@host:~# /opt/pghero/vendor/ruby-2.0.0/bin/gem install pghero
ERROR:  Error installing pghero:
        activesupport requires Ruby version >= 2.2.2.
```

**Comment by ankane** [comment]
Hey @tmitchell, I made some update to the package. Can you try the latest version?

**Comment by addykapur** [comment]
I am on Ubuntu 14.04.4 and I get the following error

[10077] * Version 3.6.0 (ruby 2.3.1-p112), codename: Sleepy Sunday Serenity
[10077] * Min threads: 1, max threads: 16
[10077] * Environment: production
[10077] * Process workers: 3
[10077] * Preloading application
[10077] ! Unable to load application: NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x007f2dab1745a0>
Did you mean?  asset_host
/opt/pghero/vendor/bundle/ruby/2.3.0/gems/railties-5.0.0.1/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `assets' for #<Rails::Application::Configuration:0x007f2dab1745a0> (NoMethodError)
Did you mean?  asset_host

**Comment by ankane** [comment]
@addykapur Seeing that now as well. Will investigate.

**Comment by ankane** [comment]
Should be fixed now - was missing a dependency.

**Comment by tmitchell** [comment]
After install of f99a06dc, I still get the error ```/opt/pghero/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'pghero'. (Bundler::GemRequireError)
        from /opt/pghero/vendor/bundle/ruby/2.3.0/gems/bundler-1.11.```

**Comment by ankane** [comment]
I'd confirm your `DATABASE_URL` doesn't have any invalid characters. This looks similar to https://github.com/bmorton/pghero_solo/issues/6.

If that doesn't work, can you paste the full stack trace from the latest error?

**Comment by ankane** [comment]
Cleaning up issues. Please reopen if you have more info.
